// Package openapiv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapiv1

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AggregatePredicateKind.
const (
	AggregatePredicateKindCompleteTuple           AggregatePredicateKind = "complete_tuple"
	AggregatePredicateKindEqualFieldAcrossSources AggregatePredicateKind = "equal_field_across_sources"
	AggregatePredicateKindLessOrEqualFields       AggregatePredicateKind = "less_or_equal_fields"
	AggregatePredicateKindNonNegativeInt          AggregatePredicateKind = "non_negative_int"
)

// Valid indicates whether the value is a known member of the AggregatePredicateKind enum.
func (e AggregatePredicateKind) Valid() bool {
	switch e {
	case AggregatePredicateKindCompleteTuple:
		return true
	case AggregatePredicateKindEqualFieldAcrossSources:
		return true
	case AggregatePredicateKindLessOrEqualFields:
		return true
	case AggregatePredicateKindNonNegativeInt:
		return true
	default:
		return false
	}
}

// Defines values for CompilerDiagnosticCode.
const (
	CompilerDiagnosticCodeDECLAREDACCESSMISMATCH  CompilerDiagnosticCode = "DECLARED_ACCESS_MISMATCH"
	CompilerDiagnosticCodeDEPENDENCYCYCLE         CompilerDiagnosticCode = "DEPENDENCY_CYCLE"
	CompilerDiagnosticCodePROFILEORDERUNPROVABLE  CompilerDiagnosticCode = "PROFILE_ORDER_UNPROVABLE"
	CompilerDiagnosticCodeUNKNOWNFIELD            CompilerDiagnosticCode = "UNKNOWN_FIELD"
	CompilerDiagnosticCodeUNSUPPORTEDOPERATOR     CompilerDiagnosticCode = "UNSUPPORTED_OPERATOR"
	CompilerDiagnosticCodeWRITECONFLICTUNRESOLVED CompilerDiagnosticCode = "WRITE_CONFLICT_UNRESOLVED"
)

// Valid indicates whether the value is a known member of the CompilerDiagnosticCode enum.
func (e CompilerDiagnosticCode) Valid() bool {
	switch e {
	case CompilerDiagnosticCodeDECLAREDACCESSMISMATCH:
		return true
	case CompilerDiagnosticCodeDEPENDENCYCYCLE:
		return true
	case CompilerDiagnosticCodePROFILEORDERUNPROVABLE:
		return true
	case CompilerDiagnosticCodeUNKNOWNFIELD:
		return true
	case CompilerDiagnosticCodeUNSUPPORTEDOPERATOR:
		return true
	case CompilerDiagnosticCodeWRITECONFLICTUNRESOLVED:
		return true
	default:
		return false
	}
}

// Defines values for CreateExecutionRequestProvenancePolicy.
const (
	CreateExecutionRequestProvenancePolicyChangesV1 CreateExecutionRequestProvenancePolicy = "changes.v1"
)

// Valid indicates whether the value is a known member of the CreateExecutionRequestProvenancePolicy enum.
func (e CreateExecutionRequestProvenancePolicy) Valid() bool {
	switch e {
	case CreateExecutionRequestProvenancePolicyChangesV1:
		return true
	default:
		return false
	}
}

// Defines values for ExecutionResultSpineStatus.
const (
	ExecutionResultSpineStatusFailed      ExecutionResultSpineStatus = "failed"
	ExecutionResultSpineStatusInvalidPlan ExecutionResultSpineStatus = "invalid_plan"
	ExecutionResultSpineStatusSucceeded   ExecutionResultSpineStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the ExecutionResultSpineStatus enum.
func (e ExecutionResultSpineStatus) Valid() bool {
	switch e {
	case ExecutionResultSpineStatusFailed:
		return true
	case ExecutionResultSpineStatusInvalidPlan:
		return true
	case ExecutionResultSpineStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for ExecutionStatus.
const (
	ExecutionStatusFailed    ExecutionStatus = "failed"
	ExecutionStatusPending   ExecutionStatus = "pending"
	ExecutionStatusRunning   ExecutionStatus = "running"
	ExecutionStatusSucceeded ExecutionStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the ExecutionStatus enum.
func (e ExecutionStatus) Valid() bool {
	switch e {
	case ExecutionStatusFailed:
		return true
	case ExecutionStatusPending:
		return true
	case ExecutionStatusRunning:
		return true
	case ExecutionStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for FieldReductionKind.
const (
	FieldReductionKindReduceInt64Max FieldReductionKind = "reduce_int64_max"
)

// Valid indicates whether the value is a known member of the FieldReductionKind enum.
func (e FieldReductionKind) Valid() bool {
	switch e {
	case FieldReductionKindReduceInt64Max:
		return true
	default:
		return false
	}
}

// Defines values for OutputKeyExpressionKind.
const (
	OutputKeyExpressionKindCommonSourceField OutputKeyExpressionKind = "common_source_field"
)

// Valid indicates whether the value is a known member of the OutputKeyExpressionKind enum.
func (e OutputKeyExpressionKind) Valid() bool {
	switch e {
	case OutputKeyExpressionKindCommonSourceField:
		return true
	default:
		return false
	}
}

// Defines values for ProfileDeclarationAggregation.
const (
	ProfileDeclarationAggregationAllSelected ProfileDeclarationAggregation = "all_selected"
)

// Valid indicates whether the value is a known member of the ProfileDeclarationAggregation enum.
func (e ProfileDeclarationAggregation) Valid() bool {
	switch e {
	case ProfileDeclarationAggregationAllSelected:
		return true
	default:
		return false
	}
}

// Defines values for ProfileDeclarationScopeKind.
const (
	ProfileDeclarationScopeKindAllEntitiesOfKind ProfileDeclarationScopeKind = "all_entities_of_kind"
)

// Valid indicates whether the value is a known member of the ProfileDeclarationScopeKind enum.
func (e ProfileDeclarationScopeKind) Valid() bool {
	switch e {
	case ProfileDeclarationScopeKindAllEntitiesOfKind:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessVerdict.
const (
	ReadinessVerdictNeedsInput ReadinessVerdict = "needs_input"
	ReadinessVerdictReady      ReadinessVerdict = "ready"
)

// Valid indicates whether the value is a known member of the ReadinessVerdict enum.
func (e ReadinessVerdict) Valid() bool {
	switch e {
	case ReadinessVerdictNeedsInput:
		return true
	case ReadinessVerdictReady:
		return true
	default:
		return false
	}
}

// Defines values for RequirementAtomKind.
const (
	RequirementAtomKindFieldPresent RequirementAtomKind = "field_present"
)

// Valid indicates whether the value is a known member of the RequirementAtomKind enum.
func (e RequirementAtomKind) Valid() bool {
	switch e {
	case RequirementAtomKindFieldPresent:
		return true
	default:
		return false
	}
}

// Defines values for SemanticFailureKind.
const (
	SemanticFailureKindArtifactIntegrityFailed  SemanticFailureKind = "artifact_integrity_failed"
	SemanticFailureKindProtectedInvariantFailed SemanticFailureKind = "protected_invariant_failed"
)

// Valid indicates whether the value is a known member of the SemanticFailureKind enum.
func (e SemanticFailureKind) Valid() bool {
	switch e {
	case SemanticFailureKindArtifactIntegrityFailed:
		return true
	case SemanticFailureKindProtectedInvariantFailed:
		return true
	default:
		return false
	}
}

// Defines values for TransformationDeclarationOperator.
const (
	TransformationDeclarationOperatorAggregateRelatedFields TransformationDeclarationOperator = "aggregate_related_fields"
	TransformationDeclarationOperatorFormRelatedEntity      TransformationDeclarationOperator = "form_related_entity"
)

// Valid indicates whether the value is a known member of the TransformationDeclarationOperator enum.
func (e TransformationDeclarationOperator) Valid() bool {
	switch e {
	case TransformationDeclarationOperatorAggregateRelatedFields:
		return true
	case TransformationDeclarationOperatorFormRelatedEntity:
		return true
	default:
		return false
	}
}

// Defines values for ValueKind.
const (
	ValueKindAtom   ValueKind = "atom"
	ValueKindInt64  ValueKind = "int64"
	ValueKindString ValueKind = "string"
)

// Valid indicates whether the value is a known member of the ValueKind enum.
func (e ValueKind) Valid() bool {
	switch e {
	case ValueKindAtom:
		return true
	case ValueKindInt64:
		return true
	case ValueKindString:
		return true
	default:
		return false
	}
}

// Defines values for WorldReferenceKind.
const (
	WorldReferenceKindConfiguration WorldReferenceKind = "configuration"
	WorldReferenceKindSnapshot      WorldReferenceKind = "snapshot"
)

// Valid indicates whether the value is a known member of the WorldReferenceKind enum.
func (e WorldReferenceKind) Valid() bool {
	switch e {
	case WorldReferenceKindConfiguration:
		return true
	case WorldReferenceKindSnapshot:
		return true
	default:
		return false
	}
}

// AggregatePredicate defines model for AggregatePredicate.
type AggregatePredicate struct {
	Fields []string               `json:"fields"`
	Kind   AggregatePredicateKind `json:"kind"`
}

// AggregatePredicateKind defines model for AggregatePredicate.Kind.
type AggregatePredicateKind string

// AggregateRelatedFields The closed related-field aggregation payload.
type AggregateRelatedFields struct {
	Anchor              FieldCopy             `json:"anchor"`
	Predicates          *[]AggregatePredicate `json:"predicates,omitempty"`
	Reductions          *[]FieldReduction     `json:"reductions,omitempty"`
	RelationKind        string                `json:"relationKind"`
	RequiredSourceTuple []string              `json:"requiredSourceTuple"`
	ResultPredicates    *[]AggregatePredicate `json:"resultPredicates,omitempty"`
	SourceKind          string                `json:"sourceKind"`
	Target              OutputSlotReference   `json:"target"`
}

// Assessment defines model for Assessment.
type Assessment struct {
	// AssessmentID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	AssessmentID Digest `json:"assessmentID"`

	// CheckpointArtifactID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	CheckpointArtifactID Digest `json:"checkpointArtifactID"`

	// Digest A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	Digest Digest `json:"digest"`

	// MissingRequirements Closed requirement codes that were not satisfied. Empty when ready.
	MissingRequirements *[]string `json:"missingRequirements,omitempty"`

	// ProfileID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	ProfileID  Digest `json:"profileID"`
	ProfileKey string `json:"profileKey"`

	// Verdict A readiness answer. `needs_input` is a successful assessment, not a failure.
	Verdict ReadinessVerdict `json:"verdict"`
}

// Checkpoint defines model for Checkpoint.
type Checkpoint struct {
	// CheckpointArtifactID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	CheckpointArtifactID Digest `json:"checkpointArtifactID"`

	// CheckpointID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	CheckpointID  Digest `json:"checkpointID"`
	CheckpointKey string `json:"checkpointKey"`

	// Digest A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	Digest Digest `json:"digest"`

	// StateDigest A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	StateDigest Digest `json:"stateDigest"`
}

// CheckpointDeclaration defines model for CheckpointDeclaration.
type CheckpointDeclaration struct {
	// After The rule whose completion this checkpoint follows.
	After string `json:"after"`
	Key   string `json:"key"`
}

// CompiledProfile defines model for CompiledProfile.
type CompiledProfile struct {
	Key string `json:"key"`

	// ProfileID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	ProfileID Digest `json:"profileID"`
}

// CompilerDiagnostic defines model for CompilerDiagnostic.
type CompilerDiagnostic struct {
	// Code A closed compilation diagnostic code.
	Code CompilerDiagnosticCode `json:"code"`
}

// CompilerDiagnosticCode A closed compilation diagnostic code.
type CompilerDiagnosticCode string

// CreateExecutionRequest defines model for CreateExecutionRequest.
type CreateExecutionRequest struct {
	// ExecutorIdentity The executing backend. It affects only `executionID` and never enters checkpoint or journal identity.
	ExecutorIdentity ExecutorIdentity `json:"executorIdentity"`
	InitialState     StateInput       `json:"initialState"`

	// PlanID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	PlanID           Digest                                 `json:"planID"`
	ProvenancePolicy CreateExecutionRequestProvenancePolicy `json:"provenancePolicy"`

	// World The pinned execution world. An empty reference list is a real, versioned empty world, not a missing value.
	World *WorldInput `json:"world,omitempty"`
}

// CreateExecutionRequestProvenancePolicy defines model for CreateExecutionRequest.ProvenancePolicy.
type CreateExecutionRequestProvenancePolicy string

// Digest A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
type Digest = string

// EntityDeclaration defines model for EntityDeclaration.
type EntityDeclaration struct {
	Fields []FieldDeclaration `json:"fields"`
	Kind   string             `json:"kind"`
}

// EntityInput One initial-state entity. The client supplies its canonical source key,
// not an entity identity: identities are derived by the kernel from the
// lineage so that a client cannot invent or collide one.
type EntityInput struct {
	CanonicalSourceKey string           `json:"canonicalSourceKey"`
	Fields             map[string]Value `json:"fields"`
	Kind               string           `json:"kind"`
}

// Execution defines model for Execution.
type Execution struct {
	// ExecutionID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	ExecutionID Digest `json:"executionID"`

	// ExecutionStatus Application control-plane lifecycle state, deliberately excluded from
	// canonical semantic identity. The semantic layer answers what a
	// computation meant; this answers what happened while it ran.
	ExecutionStatus ExecutionStatus `json:"executionStatus"`

	// FailureReason A bounded operational code present only when the execution could not
	// be attempted. It is not a semantic outcome: a computation that ran
	// and refused reports that through `result.failure`.
	FailureReason *string `json:"failureReason,omitempty"`

	// PlanID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	PlanID Digest `json:"planID"`

	// Result The complete answer of a finished execution. Present only once the
	// execution finished, so a caller must not infer one from the status alone.
	Result *ExecutionResult `json:"result,omitempty"`

	// SemanticRunID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	SemanticRunID Digest `json:"semanticRunID"`
}

// ExecutionAccepted The identities of an accepted execution, returned immediately on submission.
type ExecutionAccepted struct {
	// ExecutionID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	ExecutionID Digest `json:"executionID"`

	// ExecutionStatus Application control-plane lifecycle state, deliberately excluded from
	// canonical semantic identity. The semantic layer answers what a
	// computation meant; this answers what happened while it ran.
	ExecutionStatus ExecutionStatus `json:"executionStatus"`

	// PlanID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	PlanID Digest `json:"planID"`

	// SemanticRunID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	SemanticRunID Digest `json:"semanticRunID"`
}

// ExecutionResult The complete answer of a finished execution. Present only once the
// execution finished, so a caller must not infer one from the status alone.
type ExecutionResult struct {
	// AcceptedRules Committed transitions in accepted order. Rejections never appear here.
	AcceptedRules *[]string    `json:"acceptedRules,omitempty"`
	Assessments   []Assessment `json:"assessments"`

	// Checkpoints Sealed checkpoints in the independently verified dependency-closed frontier.
	Checkpoints []Checkpoint `json:"checkpoints"`

	// Failure A deterministic semantic rejection. Its presence does not make the HTTP
	// response an error: the run produced a real answer, and every artifact
	// verified before the rejection is retained.
	Failure *SemanticFailure `json:"failure,omitempty"`

	// FinalStateDigest A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	FinalStateDigest *Digest `json:"finalStateDigest,omitempty"`

	// InputID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	InputID *Digest `json:"inputID,omitempty"`

	// JournalPrefixDigest A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	JournalPrefixDigest *Digest                    `json:"journalPrefixDigest,omitempty"`
	SpineStatus         ExecutionResultSpineStatus `json:"spineStatus"`

	// WorldID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	WorldID *Digest `json:"worldID,omitempty"`
}

// ExecutionResultSpineStatus defines model for ExecutionResult.SpineStatus.
type ExecutionResultSpineStatus string

// ExecutionStatus Application control-plane lifecycle state, deliberately excluded from
// canonical semantic identity. The semantic layer answers what a
// computation meant; this answers what happened while it ran.
type ExecutionStatus string

// ExecutorIdentity The executing backend. It affects only `executionID` and never enters checkpoint or journal identity.
type ExecutorIdentity struct {
	Backend string `json:"backend"`

	// Version A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	Version Digest `json:"version"`
}

// FieldCopy defines model for FieldCopy.
type FieldCopy struct {
	// Destination A field path of the form kind.field.
	Destination string `json:"destination"`

	// Source A field path of the form kind.field.
	Source string `json:"source"`
}

// FieldDeclaration defines model for FieldDeclaration.
type FieldDeclaration struct {
	// Kind The closed typed-value vocabulary.
	Kind ValueKind `json:"kind"`
	Name string    `json:"name"`

	// RequiredAtConstruction Whether state construction rejects an entity of this kind that omits
	// the field. This is a representation obligation, independent of the
	// value type; rule-level presence obligations are enforced by the
	// transformations that read the field, not here.
	RequiredAtConstruction *bool `json:"requiredAtConstruction,omitempty"`
}

// FieldReduction defines model for FieldReduction.
type FieldReduction struct {
	Destination string             `json:"destination"`
	Kind        FieldReductionKind `json:"kind"`
	Source      string             `json:"source"`
}

// FieldReductionKind defines model for FieldReduction.Kind.
type FieldReductionKind string

// FormRelatedEntity The closed related-entity transformation payload.
type FormRelatedEntity struct {
	CopiedFields  *[]FieldCopy         `json:"copiedFields,omitempty"`
	GroupingField string               `json:"groupingField"`
	OutputKey     *OutputKeyExpression `json:"outputKey,omitempty"`
	OutputKind    string               `json:"outputKind"`
	OutputSlot    string               `json:"outputSlot"`
	RelationKind  string               `json:"relationKind"`
	SourceCount   int64                `json:"sourceCount"`
	SourceKind    string               `json:"sourceKind"`
	Sources       []SourceReference    `json:"sources"`
}

// InputLineage Pins the observation load that produced the initial state. Entity identities are derived from it, so a different lineage is a different input.
type InputLineage struct {
	Namespace string `json:"namespace"`
	RootKey   string `json:"rootKey"`
}

// OutputKeyExpression defines model for OutputKeyExpression.
type OutputKeyExpression struct {
	Field string                  `json:"field"`
	Kind  OutputKeyExpressionKind `json:"kind"`
}

// OutputKeyExpressionKind defines model for OutputKeyExpression.Kind.
type OutputKeyExpressionKind string

// OutputSlotReference defines model for OutputSlotReference.
type OutputSlotReference struct {
	Rule string `json:"rule"`
	Slot string `json:"slot"`
}

// Plan defines model for Plan.
type Plan struct {
	Checkpoints []CheckpointDeclaration `json:"checkpoints"`

	// Declarations The declarations as the compiler accepted them, in canonical order.
	//
	// Present on retrieval and omitted on creation, because a client that
	// just submitted declarations already holds them. This is projected
	// from the compiled plan rather than from a stored copy of the
	// request, so it shows what was compiled rather than what was sent;
	// where the two differ, the difference is the compiler's
	// canonicalization and is usually the answer being looked for.
	//
	// Operational telemetry cannot carry declarations: trace attributes
	// are limited to three identities plus closed tokens, and metrics to
	// bounded enums. This projection is therefore the only way to resolve
	// a PlanID observed in a trace back to what the plan actually says.
	Declarations *PlanDeclarations `json:"declarations,omitempty"`

	// PlanID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	PlanID   Digest            `json:"planID"`
	Profiles []CompiledProfile `json:"profiles"`

	// Rules Compiled rule identities in dependency order.
	Rules []string `json:"rules"`
}

// PlanDeclarations defines model for PlanDeclarations.
type PlanDeclarations struct {
	// CompilerSemanticsVersion The pinned compiler semantics version. Compilation is reproducible only against a fixed version.
	CompilerSemanticsVersion string                `json:"compilerSemanticsVersion"`
	Profiles                 *[]ProfileDeclaration `json:"profiles,omitempty"`
	Rules                    RulesetDeclaration    `json:"rules"`

	// Schema Declaration order is not semantic; the compiler canonicalizes it.
	Schema SchemaDeclaration `json:"schema"`
}

// Problem An RFC 9457 problem document. It never carries payloads, entity references, evidence, or internal error text.
type Problem struct {
	// Code A stable closed code token, when one classifies the problem.
	Code *string `json:"code,omitempty"`

	// Detail Fixed safe text. Never contains request payloads or dependency errors.
	Detail *string `json:"detail,omitempty"`

	// Diagnostics Closed compiler diagnostic codes, present only for a compilation failure.
	Diagnostics *[]CompilerDiagnostic `json:"diagnostics,omitempty"`
	Status      int32                 `json:"status"`

	// Title A short, stable, human-readable summary. Not a diagnostic payload.
	Title string `json:"title"`

	// Type A stable problem-type URI from the closed Maiden Lane vocabulary.
	Type string `json:"type"`
}

// ProfileDeclaration A closed consumer-completeness declaration. Ordering between profiles is proved from normalized implication, never from names.
type ProfileDeclaration struct {
	Aggregation  ProfileDeclarationAggregation `json:"aggregation"`
	Implies      *[]string                     `json:"implies,omitempty"`
	Key          string                        `json:"key"`
	Requirements []RequirementAtom             `json:"requirements"`
	Scope        struct {
		EntityKind string                      `json:"entityKind"`
		Kind       ProfileDeclarationScopeKind `json:"kind"`
	} `json:"scope"`
}

// ProfileDeclarationAggregation defines model for ProfileDeclaration.Aggregation.
type ProfileDeclarationAggregation string

// ProfileDeclarationScopeKind defines model for ProfileDeclaration.Scope.Kind.
type ProfileDeclarationScopeKind string

// ReadinessVerdict A readiness answer. `needs_input` is a successful assessment, not a failure.
type ReadinessVerdict string

// RelationDeclaration defines model for RelationDeclaration.
type RelationDeclaration struct {
	FromKind string `json:"fromKind"`
	Kind     string `json:"kind"`
	ToKind   string `json:"toKind"`
}

// RelationInput defines model for RelationInput.
type RelationInput struct {
	FromKind      string `json:"fromKind"`
	FromSourceKey string `json:"fromSourceKey"`
	Kind          string `json:"kind"`
	ToKind        string `json:"toKind"`
	ToSourceKey   string `json:"toSourceKey"`
}

// RequirementAtom defines model for RequirementAtom.
type RequirementAtom struct {
	// Code A closed readiness requirement code.
	Code  string              `json:"code"`
	Field string              `json:"field"`
	Kind  RequirementAtomKind `json:"kind"`
}

// RequirementAtomKind defines model for RequirementAtom.Kind.
type RequirementAtomKind string

// RulesetDeclaration defines model for RulesetDeclaration.
type RulesetDeclaration struct {
	Checkpoints     *[]CheckpointDeclaration    `json:"checkpoints,omitempty"`
	Transformations []TransformationDeclaration `json:"transformations"`
}

// SchemaDeclaration Declaration order is not semantic; the compiler canonicalizes it.
type SchemaDeclaration struct {
	Entities  []EntityDeclaration    `json:"entities"`
	Relations *[]RelationDeclaration `json:"relations,omitempty"`
}

// SemanticFailure A deterministic semantic rejection. Its presence does not make the HTTP
// response an error: the run produced a real answer, and every artifact
// verified before the rejection is retained.
type SemanticFailure struct {
	// Code The closed invariant, operation-invariant, or integrity code.
	//
	// The rejected rule is deliberately not reported here. A failure
	// report is a canonical semantic artifact and does not carry a rule
	// identity; the accepted rule list plus the closed code identify the
	// boundary that refused, without inventing a field the kernel cannot
	// populate truthfully.
	Code *string             `json:"code,omitempty"`
	Kind SemanticFailureKind `json:"kind"`
}

// SemanticFailureKind defines model for SemanticFailure.Kind.
type SemanticFailureKind string

// SourceReference defines model for SourceReference.
type SourceReference struct {
	CanonicalSourceKey string `json:"canonicalSourceKey"`
	Kind               string `json:"kind"`
}

// StateInput defines model for StateInput.
type StateInput struct {
	Entities []EntityInput `json:"entities"`

	// Lineage Pins the observation load that produced the initial state. Entity identities are derived from it, so a different lineage is a different input.
	Lineage   InputLineage     `json:"lineage"`
	Relations *[]RelationInput `json:"relations,omitempty"`
}

// TransformationDeclaration A closed tagged union. Exactly one payload must be present and must agree with `operator`.
type TransformationDeclaration struct {
	After *[]string `json:"after,omitempty"`

	// Aggregate The closed related-field aggregation payload.
	Aggregate      *AggregateRelatedFields `json:"aggregate,omitempty"`
	DeclaredReads  *[]string               `json:"declaredReads,omitempty"`
	DeclaredWrites *[]string               `json:"declaredWrites,omitempty"`

	// Form The closed related-entity transformation payload.
	Form     *FormRelatedEntity                `json:"form,omitempty"`
	Id       string                            `json:"id"`
	Operator TransformationDeclarationOperator `json:"operator"`
}

// TransformationDeclarationOperator defines model for TransformationDeclaration.Operator.
type TransformationDeclarationOperator string

// Value One typed scalar value. Exactly one of the payload fields must match `kind`.
type Value struct {
	// Atom Present when kind is atom.
	Atom *string `json:"atom,omitempty"`

	// Int64 Present when kind is int64.
	Int64 *int64 `json:"int64,omitempty"`

	// Kind The closed typed-value vocabulary.
	Kind ValueKind `json:"kind"`

	// String Present when kind is string. Exact UTF-8 bytes, never normalized.
	String *string `json:"string,omitempty"`
}

// ValueKind The closed typed-value vocabulary.
type ValueKind string

// WorldInput The pinned execution world. An empty reference list is a real, versioned empty world, not a missing value.
type WorldInput struct {
	References *[]WorldReference `json:"references,omitempty"`
}

// WorldReference defines model for WorldReference.
type WorldReference struct {
	// ContentDigest A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	ContentDigest Digest             `json:"contentDigest"`
	Kind          WorldReferenceKind `json:"kind"`
}

// WorldReferenceKind defines model for WorldReference.Kind.
type WorldReferenceKind string

// TenantHeader defines model for TenantHeader.
type TenantHeader = string

// BadRequest An RFC 9457 problem document. It never carries payloads, entity references, evidence, or internal error text.
type BadRequest = Problem

// DependencyUnavailable An RFC 9457 problem document. It never carries payloads, entity references, evidence, or internal error text.
type DependencyUnavailable = Problem

// InternalError An RFC 9457 problem document. It never carries payloads, entity references, evidence, or internal error text.
type InternalError = Problem

// MethodNotAllowed An RFC 9457 problem document. It never carries payloads, entity references, evidence, or internal error text.
type MethodNotAllowed = Problem

// NotFound An RFC 9457 problem document. It never carries payloads, entity references, evidence, or internal error text.
type NotFound = Problem

// UnprocessableEntity An RFC 9457 problem document. It never carries payloads, entity references, evidence, or internal error text.
type UnprocessableEntity = Problem

// UnsupportedMediaType An RFC 9457 problem document. It never carries payloads, entity references, evidence, or internal error text.
type UnsupportedMediaType = Problem

// CreateExecutionParams defines parameters for CreateExecution.
type CreateExecutionParams struct {
	// XMaidenLaneTenant The tenant that owns every artifact touched by this request. Scoping is
	// mandatory; an identifier from another tenant is reported as absent.
	XMaidenLaneTenant TenantHeader `json:"X-Maiden-Lane-Tenant"`
}

// GetExecutionParams defines parameters for GetExecution.
type GetExecutionParams struct {
	// XMaidenLaneTenant The tenant that owns every artifact touched by this request. Scoping is
	// mandatory; an identifier from another tenant is reported as absent.
	XMaidenLaneTenant TenantHeader `json:"X-Maiden-Lane-Tenant"`
}

// CreatePlanParams defines parameters for CreatePlan.
type CreatePlanParams struct {
	// XMaidenLaneTenant The tenant that owns every artifact touched by this request. Scoping is
	// mandatory; an identifier from another tenant is reported as absent.
	XMaidenLaneTenant TenantHeader `json:"X-Maiden-Lane-Tenant"`
}

// GetPlanParams defines parameters for GetPlan.
type GetPlanParams struct {
	// XMaidenLaneTenant The tenant that owns every artifact touched by this request. Scoping is
	// mandatory; an identifier from another tenant is reported as absent.
	XMaidenLaneTenant TenantHeader `json:"X-Maiden-Lane-Tenant"`
}

// CreateExecutionJSONRequestBody defines body for CreateExecution for application/json ContentType.
type CreateExecutionJSONRequestBody = CreateExecutionRequest

// CreatePlanJSONRequestBody defines body for CreatePlan for application/json ContentType.
type CreatePlanJSONRequestBody = PlanDeclarations

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Report process liveness
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// GetReadiness Report process readiness
	// (GET /readyz)
	GetReadiness(w http.ResponseWriter, r *http.Request)
	// CreateExecution Execute a compiled plan
	// (POST /v1/executions)
	CreateExecution(w http.ResponseWriter, r *http.Request, params CreateExecutionParams)
	// GetExecution Retrieve an execution
	// (GET /v1/executions/{executionID})
	GetExecution(w http.ResponseWriter, r *http.Request, executionID Digest, params GetExecutionParams)
	// CreatePlan Compile declarations into a semantic plan
	// (POST /v1/plans)
	CreatePlan(w http.ResponseWriter, r *http.Request, params CreatePlanParams)
	// GetPlan Retrieve a compiled plan
	// (GET /v1/plans/{planID})
	GetPlan(w http.ResponseWriter, r *http.Request, planID Digest, params GetPlanParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GetHealth Report process liveness
// (GET /healthz)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetReadiness Report process readiness
// (GET /readyz)
func (_ Unimplemented) GetReadiness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateExecution Execute a compiled plan
// (POST /v1/executions)
func (_ Unimplemented) CreateExecution(w http.ResponseWriter, r *http.Request, params CreateExecutionParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetExecution Retrieve an execution
// (GET /v1/executions/{executionID})
func (_ Unimplemented) GetExecution(w http.ResponseWriter, r *http.Request, executionID Digest, params GetExecutionParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreatePlan Compile declarations into a semantic plan
// (POST /v1/plans)
func (_ Unimplemented) CreatePlan(w http.ResponseWriter, r *http.Request, params CreatePlanParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetPlan Retrieve a compiled plan
// (GET /v1/plans/{planID})
func (_ Unimplemented) GetPlan(w http.ResponseWriter, r *http.Request, planID Digest, params GetPlanParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateExecution operation middleware
func (siw *ServerInterfaceWrapper) CreateExecution(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateExecutionParams

	headers := r.Header

	// ------------- Required header parameter "X-Maiden-Lane-Tenant" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Maiden-Lane-Tenant")]; found {
		var XMaidenLaneTenant TenantHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Maiden-Lane-Tenant", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Maiden-Lane-Tenant", valueList[0], &XMaidenLaneTenant, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Maiden-Lane-Tenant", Err: err})
			return
		}

		params.XMaidenLaneTenant = XMaidenLaneTenant

	} else {
		err := fmt.Errorf("Header parameter X-Maiden-Lane-Tenant is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Maiden-Lane-Tenant", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateExecution(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExecution operation middleware
func (siw *ServerInterfaceWrapper) GetExecution(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "executionID" -------------
	var executionID Digest

	err = runtime.BindStyledParameterWithOptions("simple", "executionID", chi.URLParam(r, "executionID"), &executionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "executionID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetExecutionParams

	headers := r.Header

	// ------------- Required header parameter "X-Maiden-Lane-Tenant" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Maiden-Lane-Tenant")]; found {
		var XMaidenLaneTenant TenantHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Maiden-Lane-Tenant", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Maiden-Lane-Tenant", valueList[0], &XMaidenLaneTenant, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Maiden-Lane-Tenant", Err: err})
			return
		}

		params.XMaidenLaneTenant = XMaidenLaneTenant

	} else {
		err := fmt.Errorf("Header parameter X-Maiden-Lane-Tenant is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Maiden-Lane-Tenant", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExecution(w, r, executionID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePlan operation middleware
func (siw *ServerInterfaceWrapper) CreatePlan(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreatePlanParams

	headers := r.Header

	// ------------- Required header parameter "X-Maiden-Lane-Tenant" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Maiden-Lane-Tenant")]; found {
		var XMaidenLaneTenant TenantHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Maiden-Lane-Tenant", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Maiden-Lane-Tenant", valueList[0], &XMaidenLaneTenant, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Maiden-Lane-Tenant", Err: err})
			return
		}

		params.XMaidenLaneTenant = XMaidenLaneTenant

	} else {
		err := fmt.Errorf("Header parameter X-Maiden-Lane-Tenant is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Maiden-Lane-Tenant", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePlan(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlan operation middleware
func (siw *ServerInterfaceWrapper) GetPlan(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "planID" -------------
	var planID Digest

	err = runtime.BindStyledParameterWithOptions("simple", "planID", chi.URLParam(r, "planID"), &planID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "planID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPlanParams

	headers := r.Header

	// ------------- Required header parameter "X-Maiden-Lane-Tenant" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Maiden-Lane-Tenant")]; found {
		var XMaidenLaneTenant TenantHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Maiden-Lane-Tenant", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Maiden-Lane-Tenant", valueList[0], &XMaidenLaneTenant, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Maiden-Lane-Tenant", Err: err})
			return
		}

		params.XMaidenLaneTenant = XMaidenLaneTenant

	} else {
		err := fmt.Errorf("Header parameter X-Maiden-Lane-Tenant is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Maiden-Lane-Tenant", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlan(w, r, planID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadiness)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/plans", wrapper.CreatePlan)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/plans/{planID}", wrapper.GetPlan)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/executions", wrapper.CreateExecution)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/executions/{executionID}", wrapper.GetExecution)
	})

	return r
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type DependencyUnavailableApplicationProblemPlusJSONResponse Problem

type InternalErrorApplicationProblemPlusJSONResponse Problem

type MethodNotAllowedApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type UnprocessableEntityApplicationProblemPlusJSONResponse Problem

type UnsupportedMediaTypeApplicationProblemPlusJSONResponse Problem

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth204Response struct {
}

func (response GetHealth204Response) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetHealth405ApplicationProblemPlusJSONResponse struct {
	MethodNotAllowedApplicationProblemPlusJSONResponse
}

func (response GetHealth405ApplicationProblemPlusJSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(405)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness204Response struct {
}

func (response GetReadiness204Response) VisitGetReadinessResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetReadiness405ApplicationProblemPlusJSONResponse struct {
	MethodNotAllowedApplicationProblemPlusJSONResponse
}

func (response GetReadiness405ApplicationProblemPlusJSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(405)
	_, err := buf.WriteTo(w)
	return err
}

type CreateExecutionRequestObject struct {
	Params CreateExecutionParams
	Body   *CreateExecutionJSONRequestBody
}

type CreateExecutionResponseObject interface {
	VisitCreateExecutionResponse(w http.ResponseWriter) error
}

type CreateExecution202JSONResponse ExecutionAccepted

func (response CreateExecution202JSONResponse) VisitCreateExecutionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type CreateExecution400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response CreateExecution400ApplicationProblemPlusJSONResponse) VisitCreateExecutionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateExecution404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response CreateExecution404ApplicationProblemPlusJSONResponse) VisitCreateExecutionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateExecution405ApplicationProblemPlusJSONResponse struct {
	MethodNotAllowedApplicationProblemPlusJSONResponse
}

func (response CreateExecution405ApplicationProblemPlusJSONResponse) VisitCreateExecutionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(405)
	_, err := buf.WriteTo(w)
	return err
}

type CreateExecution415ApplicationProblemPlusJSONResponse struct {
	UnsupportedMediaTypeApplicationProblemPlusJSONResponse
}

func (response CreateExecution415ApplicationProblemPlusJSONResponse) VisitCreateExecutionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type CreateExecution422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response CreateExecution422ApplicationProblemPlusJSONResponse) VisitCreateExecutionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CreateExecution500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response CreateExecution500ApplicationProblemPlusJSONResponse) VisitCreateExecutionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateExecution503ApplicationProblemPlusJSONResponse struct {
	DependencyUnavailableApplicationProblemPlusJSONResponse
}

func (response CreateExecution503ApplicationProblemPlusJSONResponse) VisitCreateExecutionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetExecutionRequestObject struct {
	ExecutionID Digest `json:"executionID"`
	Params      GetExecutionParams
}

type GetExecutionResponseObject interface {
	VisitGetExecutionResponse(w http.ResponseWriter) error
}

type GetExecution200JSONResponse Execution

func (response GetExecution200JSONResponse) VisitGetExecutionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetExecution400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response GetExecution400ApplicationProblemPlusJSONResponse) VisitGetExecutionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetExecution404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetExecution404ApplicationProblemPlusJSONResponse) VisitGetExecutionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetExecution405ApplicationProblemPlusJSONResponse struct {
	MethodNotAllowedApplicationProblemPlusJSONResponse
}

func (response GetExecution405ApplicationProblemPlusJSONResponse) VisitGetExecutionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(405)
	_, err := buf.WriteTo(w)
	return err
}

type GetExecution500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response GetExecution500ApplicationProblemPlusJSONResponse) VisitGetExecutionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlanRequestObject struct {
	Params CreatePlanParams
	Body   *CreatePlanJSONRequestBody
}

type CreatePlanResponseObject interface {
	VisitCreatePlanResponse(w http.ResponseWriter) error
}

type CreatePlan201JSONResponse Plan

func (response CreatePlan201JSONResponse) VisitCreatePlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlan400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response CreatePlan400ApplicationProblemPlusJSONResponse) VisitCreatePlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlan405ApplicationProblemPlusJSONResponse struct {
	MethodNotAllowedApplicationProblemPlusJSONResponse
}

func (response CreatePlan405ApplicationProblemPlusJSONResponse) VisitCreatePlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(405)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlan415ApplicationProblemPlusJSONResponse struct {
	UnsupportedMediaTypeApplicationProblemPlusJSONResponse
}

func (response CreatePlan415ApplicationProblemPlusJSONResponse) VisitCreatePlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlan422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response CreatePlan422ApplicationProblemPlusJSONResponse) VisitCreatePlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlan500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response CreatePlan500ApplicationProblemPlusJSONResponse) VisitCreatePlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlanRequestObject struct {
	PlanID Digest `json:"planID"`
	Params GetPlanParams
}

type GetPlanResponseObject interface {
	VisitGetPlanResponse(w http.ResponseWriter) error
}

type GetPlan200JSONResponse Plan

func (response GetPlan200JSONResponse) VisitGetPlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlan400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response GetPlan400ApplicationProblemPlusJSONResponse) VisitGetPlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlan404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetPlan404ApplicationProblemPlusJSONResponse) VisitGetPlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlan405ApplicationProblemPlusJSONResponse struct {
	MethodNotAllowedApplicationProblemPlusJSONResponse
}

func (response GetPlan405ApplicationProblemPlusJSONResponse) VisitGetPlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(405)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlan500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response GetPlan500ApplicationProblemPlusJSONResponse) VisitGetPlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Report process liveness
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// GetReadiness Report process readiness
	// (GET /readyz)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)
	// CreateExecution Execute a compiled plan
	// (POST /v1/executions)
	CreateExecution(ctx context.Context, request CreateExecutionRequestObject) (CreateExecutionResponseObject, error)
	// GetExecution Retrieve an execution
	// (GET /v1/executions/{executionID})
	GetExecution(ctx context.Context, request GetExecutionRequestObject) (GetExecutionResponseObject, error)
	// CreatePlan Compile declarations into a semantic plan
	// (POST /v1/plans)
	CreatePlan(ctx context.Context, request CreatePlanRequestObject) (CreatePlanResponseObject, error)
	// GetPlan Retrieve a compiled plan
	// (GET /v1/plans/{planID})
	GetPlan(ctx context.Context, request GetPlanRequestObject) (GetPlanResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(w http.ResponseWriter, r *http.Request) {
	var request GetReadinessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx, request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		if err := validResponse.VisitGetReadinessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateExecution operation middleware
func (sh *strictHandler) CreateExecution(w http.ResponseWriter, r *http.Request, params CreateExecutionParams) {
	var request CreateExecutionRequestObject

	request.Params = params

	var body CreateExecutionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateExecution(ctx, request.(CreateExecutionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateExecution")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateExecutionResponseObject); ok {
		if err := validResponse.VisitCreateExecutionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetExecution operation middleware
func (sh *strictHandler) GetExecution(w http.ResponseWriter, r *http.Request, executionID Digest, params GetExecutionParams) {
	var request GetExecutionRequestObject

	request.ExecutionID = executionID
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetExecution(ctx, request.(GetExecutionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetExecution")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetExecutionResponseObject); ok {
		if err := validResponse.VisitGetExecutionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePlan operation middleware
func (sh *strictHandler) CreatePlan(w http.ResponseWriter, r *http.Request, params CreatePlanParams) {
	var request CreatePlanRequestObject

	request.Params = params

	var body CreatePlanJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePlan(ctx, request.(CreatePlanRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePlan")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePlanResponseObject); ok {
		if err := validResponse.VisitCreatePlanResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPlan operation middleware
func (sh *strictHandler) GetPlan(w http.ResponseWriter, r *http.Request, planID Digest, params GetPlanParams) {
	var request GetPlanRequestObject

	request.PlanID = planID
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPlan(ctx, request.(GetPlanRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPlan")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPlanResponseObject); ok {
		if err := validResponse.VisitGetPlanResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5Dzbchs3lr+C6p2n3RYlO052Ij9pJDpRxZFVlJzsVOgloe5DEmM00AHQkhiXqvYj9gv3S7bOAfrK5qVl",
	"T5Kq8YtFstE4OPcrPkWJznKtQDkbnX6Kcm54Bg4MfboFxZX7HngKBj+nYBMjcie0ik6j2xUwR08wt+KO",
	"6QdlGdyDWTNunFjwxDGni2QFKbtbM7cSlhn4tQDrRuwm0blQSybsVGVcpdxps37NuGIiBeXEQoBhC6Mz",
	"xpV2KzDlVvSSXBsHKeOW8TsLyo2mKoojgVCtPLRxpHgG0Wn0X0c/cnzl0Vuu4MifKIojBEQYSKNTZwqI",
	"I5usION4yIw/vgW1dKvo9MXLv8ZRJlT1OY5y7hwY3Oi/f+FHv50cffsh/H/04d//EsWRW+e4rXVGqGX0",
	"9PSEe9lcKwuE07/xdOKRgJ8SrRwo+pPnuRQJR+Qe50bfScj+4x8WMf2pAd1fDCyi0+jfjmu6Hftf7fG1",
	"X+U33aRVwD174JZlXC60ySBl2jBXE9Jjjx4JmI2e4ugCclApqGT9XvF7LiS/k/B7gn/GSnqxtIKFoCxq",
	"gEasecqMr9kdfnRGQErHuFRIOi7Hxmjzu4KvmAh7s4wnK6FQSIRKtLLCOjqMTpLCmADpj+BWOr3S7kxK",
	"/YBc+nuzitWFSYClGixT2jFb5Ch0xCsBxZCyjOAkkK+0e6ML9buCeqWZLZJVrW7gUVhn2YKYWtjA1QTf",
	"e5UbnYC1yCpj5YRb/5EC+ABSsiCCd4XHawqJ5IYAsCiXCVdaiYRLJlReODtVD2DwNf+AxEE6Yuc6y4Wk",
	"BWzBhSwMWJZwY1DbgjAsFXyptHUiYYlOwaKeJFwEckL6I6SC35LO+mOQcadTL8nIZc1dcbdRhIvDG3HD",
	"s+XSwJI7uDaQ4pMEN09TgWu4vDY6B+ME6toFlxbiKG989SlaCJAp/SUcZPRHR2NXKpwbw9f4+aPwbA2q",
	"yKLTX8hkSnAwc0UuAU2NVjOFYIl7mAmyL/BrweWMdpvxxGhrZ16kbBRHEqydaTNrPGSjD5u2o2mmfvFg",
	"xNHG4/oO+QEBrbAzAckdpG+qw+7E0CZxEqktpMz41xzRloyHtyO35XwtNU9HURe/XCUrr1x38QYBdq5z",
	"Qm9ekrJNll3re9igh24G0iIhaTr4xQTYpFzX/1IvcD8EptjgnpJkN0TuW2KRQexmwBbSXf+zsOLZcCv4",
	"jpsluH1bvStcXrgbqd0EFmBAJbDBr+FNHZS1AOjHVlxyUS+PWwvWZqWaOlzyebXw8mLf8S7EEh20pzhK",
	"VpB8zLVQ7iwYmSGrU//Xwc9nwlqhlhOPlKz0ytsCel4KZ/WQV+7eCycTQRabO2EX6PuwcZa7NXtYgWIG",
	"eLpGsT2cH3OjF0LCkHOHJT/AuneHezCpSPbiZQI8FQqs/Sk83+WwFkkrbG8hWvMgLQhrePr47bx610B+",
	"+zzOqVc/b9U21A/lSOu4g4tBizpEasPUOdlWWlW0bAKwmz4Xtfs0VDUs3LYA1xQS2MNKW2DB7KP5I+ey",
	"hpwtNPrpdrQZ/8XRx15KdG07ocbD0XtK8vQgvfZsO/B8H7cww2DJ7oW6fssOyM1F5YoOlSOdwiZtzkof",
	"JWn4wB13F8lR+mzvr364evfz1ezN5fgt8tf7q5v319fvJrfji9m76/Hk7PbdJIqji/H527PJ+GJ2dn4+",
	"vrmZ/Xh58+PZ7fn3URz9PLm8Hc/O3129eXt5fjt7fzUZ37x7+9P4gpZdj68uxlfnf5+d//387TiKo+vJ",
	"uzeXb8ezd5OL8WT2/up68u6ns7+9He/38+jAvag0wB2MHyEp8LiNNMIAdAIt1+aS0iw+CNpF+nH3+ac4",
	"Eko4weWNC/73rvX00CXGL8RxkquBhuQeY7gErrUUybrlhq+4WoId3b/owWkcPWgj0307/YwPBeg6ZAig",
	"dk4bbyKwB8o+6tVKdIOTfdgVMl9uzXKj0yIp02bALGRcIVd/BKNAxsyASsH4DJhd8Zdff3M6LU5Ovkq+",
	"ecWkfgCTcAtsBY/0LYzYuRR4bpYV1jGHfMSEw9U6578WwLhK/W8K7sEwA4irwgETjqTokWfkx0Zht5PP",
	"/Be1Mmnhpb+cHH3LjxYfPn3z6ukvfarUh+3P1/M9wd/eYKC5247Y8HNDN380z4nD4rV3Clhg0SMylsxz",
	"kU+HJUR4St9IAZYJZxt5hZDl+QjreKooAFdhdcWMp+VfuJobYCkYcV/zpmdJn6p1K5gqKRTwJTCrvUPK",
	"SxgSTlsIdY+ftGGJllKkwLQCn8DtKP4STB8bbPNoFnuC3N00/onLohkm1RQZRNkeWHeTu1Tiz9LeQg9S",
	"otUiVGGFPUzj148jjn1yaQI8pIC6KuxOFyqFlCGs3J+FTDDLDVgit5IhAkGmqSBiiS5kivHKVN0BQ5WQ",
	"5ZTbuqRUP/Fkrf904RKdwSkyFSkoHtwx7pjhaqpQjxlYFD5AyrVxISxyK6OL5YrNfXQ9Cieae8bb9IwG",
	"2in/1oMxO/GPo38djjYp1LPdsCZTdN8Y13asywY7+fIsSQAJ8YzkUUNf6AVqFB7eVZMdLZgrjIKUiSyD",
	"VHAHcs20Yra4oyBYq83c0h/E/EN54c9K0knFo0OzgSHfybiyD2CIqmwhlLCrJlFH7Lop7Fol4C1CLe3l",
	"ohitA2cJlxJMcDzINCzw9Qoqc8IsHYxxucVIlLw1KST05Up0lgmHvOcMV1b43Lpo8KQ2KZgRm1BSnX71",
	"LhDPc+CGrcDAsHRJnZQYkLmrk1o9b6wDzZ4T3gCXGAbVz+DxEHVClbUyJ9fsHoxYiFYB7SiEUAujlRNg",
	"WufcBW4jJ9IDblCtewODwNRvwuNkylXwsy8GpimoQDJESP+hC0P8DwvxOHQ3mwsFtT4pAxJbJAlACuTq",
	"cQzXKXq451KkM5TZ7XHKsxVFE5Q2p7Q5cadmqI/Sset1OYaCFKPlEZ4DmBQLSNaJ9AIKMUtBiju0/ajH",
	"4TGRReo5K5uqhr9ZGvLSu/ROavW15GsUPVIzlj2Q+zhVTVOfAVfutU/AtJ5bocCiQXlYCYlxCzoEXmOU",
	"9EG+R6THkSmU8n/10KyPSOOeqHmgFg1aUC3ZHU8+gvI+Dl8sIHHWq8x5Q+3PKSbzugiUw3M2Ek7asMDB",
	"NSo3dGPYx/d1bGtbGPX3LVBS1AYH9Rl8We5dv6ePA+s60DA3OAXrhKpCwK436utVOXcrtFWoCxfaZAx9",
	"9RH91puo88HQl3pfV079y+MW6FtR8vwQt4xa9sY8VH95KttkdtSxzty5VtaZUBIj9Cw4eRK9vP7zCqhf",
	"x8eiSWNtqFzbRpRJ6BSWUBm6iDLh7FQRkgm17BYfQHFHj957GF4X6DspfD0ybhq7QKMpKt4CGB7sNeVx",
	"jyTcgwwhSQKN9T6yBbXQpk67TBX5DEjq8JCPM4CnrAIvJseFvIRmJHGntQSuNtiAsB1iy63Ur+uPnyUV",
	"m5noTh2b6qNUsP7m1Szjj72ar5aKgwLhw/lcmyyUqcfPVamdMnXgqTbVtpeqE52LZo388JxQWbnuej5L",
	"o4tcqCU91EsCTXXTkMrYX2D9AdbjR+RXG9JPYf224q2uyrJbRHpP7dpT71wXvtrlkRidRsQiEfXCiQyZ",
	"56Q6vFAOlmAOqCyX/Q+HotqnUhr15S7Ce1Vsq8iMXlADZS0EdcnVPn0HWX0cTMm6tz7bNZB5rwVpE1RB",
	"Fsy9Z1TkUq9iqvyvd+Mpt+f16YiNW+m5blKO4ibhQnyVigUhz7EyKUdqtP6a3OZNyUAtZXOebDEMWm8p",
	"L/YoO/+aelEfIvt4/RmJ3YN0XqKzTKvQi+Nbb4Z13uw4QbsdYtgJ0D71S02/MHcgpOXh4T4ArzH6eG79",
	"+nCR7S/G9mjKZqvb3kYyydVF8/nn1ZEWQg5QPt2Ca1+fztaUA630peOGnArVbF71eYcBmYVt5SkPRjf2",
	"qw68jRsuOhQYVJH1Jd0ygrc/1aHCppHOhVJVnRb9wnIVC5FBu4/R93eTAhR3EnxgxJdcKOso7fQIabWy",
	"N3U7lNSBxHs4tqL2zo4VfAi6zH9Yv+QN/d9aulEY3oL3aosSzF6ih37MYZbqTLHJm3P27auv/5OFPlCW",
	"6qTIQDkKYH2EmnBjkMeDs2Xj0sE3pT7Er+5RGhKIMXytGqLBGG2Yg0fX56L11/6t48gbVQtACszpj6Bi",
	"X2LQCn/j1oqFAG9oA+y9HJOC40Ju7vOGeM3yBXjw2JU/q1YO2bFqYS0PjcdqSDgdrL8npG5U2N7fVQlM",
	"t4k3bhdVFtqEckinFfjwdN5mi0Zf32CVJGq6hV+9RLeQP3q38Otvv204iS9Oet1EJ5zsp+pKG3RdiLgx",
	"WxUZV0cYbhGxbZFl3KxH7IpqQg2sNDz8LTp0KwcFtjjCx9j7yWWdeA685YdH2FuugN3rhN8VEoFo1cRX",
	"zuX29Pg484MmkisY6dyJjMt0rXgmEjtKdFb2UdvjkBOkXBr6FSU+CyP2JhLo1xKJFVW2CHxXrw2U/VrA",
	"lC0yMEdlJUCBtc129RF7h+aMklvgHgAUK9UwKnTqjwjOqcLDSvEblX6q9GIc9Ih/BP3Gntbiuv+46dFx",
	"KWcWJLXE90awtA0M7fneUm02ndbMgwSs0c955nTWK12Jzof6jF7Fbo23uq4vIqp0RmZ6MeskIXb7vo29",
	"Nnmtty3Mnyhuka2Dvz6u3Wj67BFeUz4TUsAjNlcAqZ1RPDP3UQ5ldq1dFJLVifA4VJQbKrLOhvAU4W68",
	"qZedJiEu/Iw2FKOzvVTb5FD9w6Bek3KTamU/tv1hDms8GXAM/HF338bwg+JPu965FxFtoKqd2u/tR1Nb",
	"gL9oB2PNzd2W7l6Ldnis66dPgrNwYN9hvD/Y7XFy/0SRZSdne/AGt611OzfpWuTOjn0423Tuh5nixkof",
	"OZbNMWU09do7LaXPWJXcxG/U9NXTTBEswcEI2my+2zEdM8Q2ysEYr2DvRXWnrjzU50nBgUEflnzLqjRp",
	"ygYBjHpsXUSoJiQz/pH6Hdj3t7fXU1UO/VKxAyOBUz87Wag6vcdR9mUwYjEV/Nrz01NVle3vYKENhPnL",
	"AIoPljEYgbS3g65X8TQy5+iIGsHRLladW0fNL32ctjQYypFGmqqpul3VQ4ghy2HbBWDERzWlTcURdlba",
	"XEQNjZKSle6pDVfTnIiPCr1+rJHTflNVFj0921fNHASMFBiTycI2/XiKEcNoeajuUM8ap1lJKutQ11jM",
	"HoRb6aLsU0SXlocCYKPd0fcyTlWu80JyB8yZwq0WhZTrLR1lXeWcG+0Ig7MK37OqaaBEwazC/mxrcbrP",
	"6vXKRSedPlBnH9aM+blNk72A1x3kz/CPh6u4qlm9q9xknevf9ZZWXeCzdOIWSDrYLMGKd+vF7QbumVGh",
	"48slpKxQpBTHjzxx1PYFZUDuG7vu6ibQqsucLw0ASRqbe8Wjzbwn4ivncgZ0X5UzkAcPS7ZnZavcNKQY",
	"iQyMGsulPxvhhkacSJq91ceNoinGt1tqgQGvLY9Qm2wWyqWzanyhwln106EjyYJqauVGfVzn+6uHd7Tj",
	"i1JmEy65YVTIb7NY6MMoOc0D7Jkr4y5ZsTkqmT6eCv57pyAXOJTSh9SMgNbJ6f6EoS+HHvYSenbUzPKU",
	"xdTNzNjg5o0A0mGQ+IcDGtn72zdHf2V3awe2TL7UqZn9/SxbzUwN3y7Hg8h75Bs0Omm1spnO7xt7gpU4",
	"7wvIGzM8w1sIQnWiblGldrwRO1MMaGq2SmB7vyL0oXAZl0UIXO3na3FlmWAIk7yBdTe4sE6LH2wU6Ji7",
	"q+EbxOisGRq20ljS0ObIrqNjFc/tigruiVYLsSxMtytkj5vQgqMn+0QSudD9DIfeOLOFWfAEGF2xQu2w",
	"IsslBdq+3aeR5g0uLrq0oc6BRCc3s3ArbYSjex7YgzDguyJ54kbsO80sGBQjBI+q8lO1BEUucVWYf82E",
	"n2sggev8/J1uDGr562uqJ6YqZKabcKXCAGpEAnlMkcP8+P7FvHbmWXUJCqN8XMr8hAQh2Z9q3ndD0nyq",
	"/FVAI3ZWuBWaiqR6YQqSzEXKnA4Xl+RSrwkk/P6Br0mA6ijmDqRWS5QHp/dc6DR/dfJqXmqk+auTr+Zx",
	"OUqE7jZl8igKXnQuizJwD1xSsLAir/2OvHhn/a0wKACEpzMZak6WFRbq6tZ825Un85gJlcgixbdWdzn5",
	"GMLowmEw7izIRRnY2VMErVBkiCA0DvqBB9Qec6Xd0QKDj3lVUuMqnSpaVN3MEi7XaS703xzheu4vBqre",
	"EDo+GvxST12xFCj88bFlCMO896WDqfWY2Rb7hrGbaiCnimh9IhWPWEYzU1WFM8RqvJOarZNdYeie2lea",
	"DOBHaexUGe7ZZMUVft+tPtqY3UHCkYZl6qNsEu4E2IhZShOTmJSa3jfOcLtWycpopQs7YjfV9EmF9rqA",
	"/zoE3wjeVPn5AHQSwte8Mf3khx84moSPYNiK22qIImUiXFcW6mBRs8R0dn3ZaJk9jU5GL0YnwZtTPBfR",
	"afQVfUXzkyvS08cr4NKtfsO/w9UdFSCXaXQafQfue3ok6txF9vLkVb/SbIIUrk0iyyfFPdBtSq9Ovt5m",
	"EaodjjdusaLLfHwZLzqNJj4NUL4f342MgZjhS4sGwB8s+oDrjik/v/OQVengs86ZVBNLZYHX/rOObBoA",
	"9575/sVx5Zn4+/l07wgxgYsqIjdwL3Rh5brMBaYsl1xRlbh2cjRNuJTOT+gwmyrfsotiG7yg29asnrDs",
	"1wKK0ogUKEIN8ZHr1yzXUk7V/LvxLWsDf/yp0dv+NCd4UDeX8z1klWgyD4W0IYeCRDDLtaPyjW+KhxQ1",
	"Uf1DsmYfYY3G5Y7ihLBTnSfyZqvRI9caqy4L+S2NI6VOUJOiZqV0HsLkKCHk31pfzFUpC3orz6Cnkz+h",
	"4X07VQodhUSr1uTU+Yp7+0gl/XpEErFUT4UDeRh2quatiTC/QWl8Wg1+LTjK5J0Jmpw1iMeC0h6xs3Is",
	"64GX6S9PGSZCZwVHGiOlbY/qe03NCOoelCCv+cGgpjTMuwB+9ipMBLdVPP0QMBM8qTtYcWRn440V8ot+",
	"UPXwidejbT3QuSSBFGV9p+Uv/QJcP3LcuvPy6YP3SMG6v+l014Vxw+5G23KTw1PbA3amgKcNVfbyi0Gx",
	"Oey55a62RnTEbZVt9YnwTiNq31zna9/OH7hoiOEsjab1RjP45UFnkEGyut7Sd8IESW16iTX83o3kkoxJ",
	"uC7Qp3xr2a1P1PYwGrpkqjaUSXmzqb9h79XJyX5j0bgKlJa82r+kumXx+QYpjl69OGBh7x2BuPjly0MW",
	"b162+BRHXx+ClfYtnbTqq/2r+q8obVtfz+9QdUsF29gwvg1j22OA2zas4Ym0JWZSzZ135+QKu8GQXKWx",
	"Z3rhyE+sRmS90FSztw3reFZOsc99c81GM1jfbG7HuZ+qzcqWT25sLg73HwX5LVv9uE/iTNW8nKU/3eeI",
	"V5Uuq0Mc3CoSbbj8vKflcN66i4AwUJu7//uf/w0v5qG+03cnQQZcUSzafxMBa15EwLy+kH2m5jtwX8rO",
	"xH3eaaljGh5YY9aPbjvGIKC+67g9Nb79iuOD5vk+bFieky9vefZanLg2/aUXsuiKyuhPr3Gfo/g6gYMz",
	"Au6hpTz2KC7UbTuChtD1Sa1SRJaYyqcWgpfd6vWru/kUZXDQvBfUQjlVuM+IXUuumiayutUocDEJvde7",
	"LRcaTWnj2lsuH/jasrXP59f+tG939y7spW+fbN+XG1QN42z+6uXLOrNCdeNS2n322U8U9/bW+vhCN/fb",
	"4mFee8vxJ3QuN+clDnErX3zR/bfJdYtklRX2TEXG+Pmy/K/gDLV0QhDgNk4DKivj3nFwvE5oq4jjT57Z",
	"n3blVr4Au/fauMBxR6Wty5tqZIuZq0df/rwWbpcQtLzPfynjtdXxrviS7s/B4N8z2O6UHT4pEmBGa+pw",
	"K4yMTqNj0qzhzZuV0Xa2MWSeQh5uVDNZyMNtcm0139WSseZSf5jNlTfNBQ3fvMeBs9HTh6f/DwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
