// Package openapiv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapiv1

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AggregatePredicateKind.
const (
	AggregatePredicateKindCompleteTuple           AggregatePredicateKind = "complete_tuple"
	AggregatePredicateKindEqualFieldAcrossSources AggregatePredicateKind = "equal_field_across_sources"
	AggregatePredicateKindLessOrEqualFields       AggregatePredicateKind = "less_or_equal_fields"
	AggregatePredicateKindNonNegativeInt          AggregatePredicateKind = "non_negative_int"
)

// Valid indicates whether the value is a known member of the AggregatePredicateKind enum.
func (e AggregatePredicateKind) Valid() bool {
	switch e {
	case AggregatePredicateKindCompleteTuple:
		return true
	case AggregatePredicateKindEqualFieldAcrossSources:
		return true
	case AggregatePredicateKindLessOrEqualFields:
		return true
	case AggregatePredicateKindNonNegativeInt:
		return true
	default:
		return false
	}
}

// Defines values for CompilerDiagnosticCode.
const (
	CompilerDiagnosticCodeDECLAREDACCESSMISMATCH  CompilerDiagnosticCode = "DECLARED_ACCESS_MISMATCH"
	CompilerDiagnosticCodeDEPENDENCYCYCLE         CompilerDiagnosticCode = "DEPENDENCY_CYCLE"
	CompilerDiagnosticCodePROFILEORDERUNPROVABLE  CompilerDiagnosticCode = "PROFILE_ORDER_UNPROVABLE"
	CompilerDiagnosticCodeUNKNOWNFIELD            CompilerDiagnosticCode = "UNKNOWN_FIELD"
	CompilerDiagnosticCodeUNSUPPORTEDOPERATOR     CompilerDiagnosticCode = "UNSUPPORTED_OPERATOR"
	CompilerDiagnosticCodeWRITECONFLICTUNRESOLVED CompilerDiagnosticCode = "WRITE_CONFLICT_UNRESOLVED"
)

// Valid indicates whether the value is a known member of the CompilerDiagnosticCode enum.
func (e CompilerDiagnosticCode) Valid() bool {
	switch e {
	case CompilerDiagnosticCodeDECLAREDACCESSMISMATCH:
		return true
	case CompilerDiagnosticCodeDEPENDENCYCYCLE:
		return true
	case CompilerDiagnosticCodePROFILEORDERUNPROVABLE:
		return true
	case CompilerDiagnosticCodeUNKNOWNFIELD:
		return true
	case CompilerDiagnosticCodeUNSUPPORTEDOPERATOR:
		return true
	case CompilerDiagnosticCodeWRITECONFLICTUNRESOLVED:
		return true
	default:
		return false
	}
}

// Defines values for CreateExecutionRequestProvenancePolicy.
const (
	CreateExecutionRequestProvenancePolicyChangesV1 CreateExecutionRequestProvenancePolicy = "changes.v1"
)

// Valid indicates whether the value is a known member of the CreateExecutionRequestProvenancePolicy enum.
func (e CreateExecutionRequestProvenancePolicy) Valid() bool {
	switch e {
	case CreateExecutionRequestProvenancePolicyChangesV1:
		return true
	default:
		return false
	}
}

// Defines values for ExecutionExecutionStatus.
const (
	ExecutionExecutionStatusFailed    ExecutionExecutionStatus = "failed"
	ExecutionExecutionStatusPending   ExecutionExecutionStatus = "pending"
	ExecutionExecutionStatusRunning   ExecutionExecutionStatus = "running"
	ExecutionExecutionStatusSucceeded ExecutionExecutionStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the ExecutionExecutionStatus enum.
func (e ExecutionExecutionStatus) Valid() bool {
	switch e {
	case ExecutionExecutionStatusFailed:
		return true
	case ExecutionExecutionStatusPending:
		return true
	case ExecutionExecutionStatusRunning:
		return true
	case ExecutionExecutionStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for ExecutionSpineStatus.
const (
	ExecutionSpineStatusFailed      ExecutionSpineStatus = "failed"
	ExecutionSpineStatusInvalidPlan ExecutionSpineStatus = "invalid_plan"
	ExecutionSpineStatusSucceeded   ExecutionSpineStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the ExecutionSpineStatus enum.
func (e ExecutionSpineStatus) Valid() bool {
	switch e {
	case ExecutionSpineStatusFailed:
		return true
	case ExecutionSpineStatusInvalidPlan:
		return true
	case ExecutionSpineStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for FieldReductionKind.
const (
	FieldReductionKindReduceInt64Max FieldReductionKind = "reduce_int64_max"
)

// Valid indicates whether the value is a known member of the FieldReductionKind enum.
func (e FieldReductionKind) Valid() bool {
	switch e {
	case FieldReductionKindReduceInt64Max:
		return true
	default:
		return false
	}
}

// Defines values for OutputKeyExpressionKind.
const (
	OutputKeyExpressionKindCommonSourceField OutputKeyExpressionKind = "common_source_field"
)

// Valid indicates whether the value is a known member of the OutputKeyExpressionKind enum.
func (e OutputKeyExpressionKind) Valid() bool {
	switch e {
	case OutputKeyExpressionKindCommonSourceField:
		return true
	default:
		return false
	}
}

// Defines values for ProfileDeclarationAggregation.
const (
	ProfileDeclarationAggregationAllSelected ProfileDeclarationAggregation = "all_selected"
)

// Valid indicates whether the value is a known member of the ProfileDeclarationAggregation enum.
func (e ProfileDeclarationAggregation) Valid() bool {
	switch e {
	case ProfileDeclarationAggregationAllSelected:
		return true
	default:
		return false
	}
}

// Defines values for ProfileDeclarationScopeKind.
const (
	ProfileDeclarationScopeKindAllEntitiesOfKind ProfileDeclarationScopeKind = "all_entities_of_kind"
)

// Valid indicates whether the value is a known member of the ProfileDeclarationScopeKind enum.
func (e ProfileDeclarationScopeKind) Valid() bool {
	switch e {
	case ProfileDeclarationScopeKindAllEntitiesOfKind:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessVerdict.
const (
	ReadinessVerdictNeedsInput ReadinessVerdict = "needs_input"
	ReadinessVerdictReady      ReadinessVerdict = "ready"
)

// Valid indicates whether the value is a known member of the ReadinessVerdict enum.
func (e ReadinessVerdict) Valid() bool {
	switch e {
	case ReadinessVerdictNeedsInput:
		return true
	case ReadinessVerdictReady:
		return true
	default:
		return false
	}
}

// Defines values for RequirementAtomKind.
const (
	RequirementAtomKindFieldPresent RequirementAtomKind = "field_present"
)

// Valid indicates whether the value is a known member of the RequirementAtomKind enum.
func (e RequirementAtomKind) Valid() bool {
	switch e {
	case RequirementAtomKindFieldPresent:
		return true
	default:
		return false
	}
}

// Defines values for SemanticFailureKind.
const (
	SemanticFailureKindArtifactIntegrityFailed  SemanticFailureKind = "artifact_integrity_failed"
	SemanticFailureKindProtectedInvariantFailed SemanticFailureKind = "protected_invariant_failed"
)

// Valid indicates whether the value is a known member of the SemanticFailureKind enum.
func (e SemanticFailureKind) Valid() bool {
	switch e {
	case SemanticFailureKindArtifactIntegrityFailed:
		return true
	case SemanticFailureKindProtectedInvariantFailed:
		return true
	default:
		return false
	}
}

// Defines values for TransformationDeclarationOperator.
const (
	TransformationDeclarationOperatorAggregateRelatedFields TransformationDeclarationOperator = "aggregate_related_fields"
	TransformationDeclarationOperatorFormRelatedEntity      TransformationDeclarationOperator = "form_related_entity"
)

// Valid indicates whether the value is a known member of the TransformationDeclarationOperator enum.
func (e TransformationDeclarationOperator) Valid() bool {
	switch e {
	case TransformationDeclarationOperatorAggregateRelatedFields:
		return true
	case TransformationDeclarationOperatorFormRelatedEntity:
		return true
	default:
		return false
	}
}

// Defines values for ValueKind.
const (
	ValueKindAtom   ValueKind = "atom"
	ValueKindInt64  ValueKind = "int64"
	ValueKindString ValueKind = "string"
)

// Valid indicates whether the value is a known member of the ValueKind enum.
func (e ValueKind) Valid() bool {
	switch e {
	case ValueKindAtom:
		return true
	case ValueKindInt64:
		return true
	case ValueKindString:
		return true
	default:
		return false
	}
}

// Defines values for WorldReferenceKind.
const (
	WorldReferenceKindConfiguration WorldReferenceKind = "configuration"
	WorldReferenceKindSnapshot      WorldReferenceKind = "snapshot"
)

// Valid indicates whether the value is a known member of the WorldReferenceKind enum.
func (e WorldReferenceKind) Valid() bool {
	switch e {
	case WorldReferenceKindConfiguration:
		return true
	case WorldReferenceKindSnapshot:
		return true
	default:
		return false
	}
}

// AggregatePredicate defines model for AggregatePredicate.
type AggregatePredicate struct {
	Fields []string               `json:"fields"`
	Kind   AggregatePredicateKind `json:"kind"`
}

// AggregatePredicateKind defines model for AggregatePredicate.Kind.
type AggregatePredicateKind string

// AggregateRelatedFields The closed related-field aggregation payload.
type AggregateRelatedFields struct {
	Anchor              FieldCopy             `json:"anchor"`
	Predicates          *[]AggregatePredicate `json:"predicates,omitempty"`
	Reductions          *[]FieldReduction     `json:"reductions,omitempty"`
	RelationKind        string                `json:"relationKind"`
	RequiredSourceTuple []string              `json:"requiredSourceTuple"`
	ResultPredicates    *[]AggregatePredicate `json:"resultPredicates,omitempty"`
	SourceKind          string                `json:"sourceKind"`
	Target              OutputSlotReference   `json:"target"`
}

// Assessment defines model for Assessment.
type Assessment struct {
	// AssessmentID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	AssessmentID Digest `json:"assessmentID"`

	// CheckpointArtifactID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	CheckpointArtifactID Digest `json:"checkpointArtifactID"`

	// Digest A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	Digest Digest `json:"digest"`

	// MissingRequirements Closed requirement codes that were not satisfied. Empty when ready.
	MissingRequirements *[]string `json:"missingRequirements,omitempty"`

	// ProfileID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	ProfileID  Digest `json:"profileID"`
	ProfileKey string `json:"profileKey"`

	// Verdict A readiness answer. `needs_input` is a successful assessment, not a failure.
	Verdict ReadinessVerdict `json:"verdict"`
}

// Checkpoint defines model for Checkpoint.
type Checkpoint struct {
	// CheckpointArtifactID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	CheckpointArtifactID Digest `json:"checkpointArtifactID"`

	// CheckpointID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	CheckpointID  Digest `json:"checkpointID"`
	CheckpointKey string `json:"checkpointKey"`

	// Digest A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	Digest Digest `json:"digest"`

	// StateDigest A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	StateDigest Digest `json:"stateDigest"`
}

// CheckpointDeclaration defines model for CheckpointDeclaration.
type CheckpointDeclaration struct {
	// After The rule whose completion this checkpoint follows.
	After string `json:"after"`
	Key   string `json:"key"`
}

// CompiledProfile defines model for CompiledProfile.
type CompiledProfile struct {
	Key string `json:"key"`

	// ProfileID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	ProfileID Digest `json:"profileID"`
}

// CompilerDiagnostic defines model for CompilerDiagnostic.
type CompilerDiagnostic struct {
	// Code A closed compilation diagnostic code.
	Code CompilerDiagnosticCode `json:"code"`
}

// CompilerDiagnosticCode A closed compilation diagnostic code.
type CompilerDiagnosticCode string

// CreateExecutionRequest defines model for CreateExecutionRequest.
type CreateExecutionRequest struct {
	// ExecutorIdentity The executing backend. It affects only `executionID` and never enters checkpoint or journal identity.
	ExecutorIdentity ExecutorIdentity `json:"executorIdentity"`
	InitialState     StateInput       `json:"initialState"`

	// PlanID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	PlanID           Digest                                 `json:"planID"`
	ProvenancePolicy CreateExecutionRequestProvenancePolicy `json:"provenancePolicy"`

	// World The pinned execution world. An empty reference list is a real, versioned empty world, not a missing value.
	World *WorldInput `json:"world,omitempty"`
}

// CreateExecutionRequestProvenancePolicy defines model for CreateExecutionRequest.ProvenancePolicy.
type CreateExecutionRequestProvenancePolicy string

// Digest A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
type Digest = string

// EntityDeclaration defines model for EntityDeclaration.
type EntityDeclaration struct {
	Fields []FieldDeclaration `json:"fields"`
	Kind   string             `json:"kind"`
}

// EntityInput One initial-state entity. The client supplies its canonical source key,
// not an entity identity: identities are derived by the kernel from the
// lineage so that a client cannot invent or collide one.
type EntityInput struct {
	CanonicalSourceKey string           `json:"canonicalSourceKey"`
	Fields             map[string]Value `json:"fields"`
	Kind               string           `json:"kind"`
}

// Execution defines model for Execution.
type Execution struct {
	// AcceptedRules Committed transitions in accepted order. Rejections never appear here.
	AcceptedRules *[]string    `json:"acceptedRules,omitempty"`
	Assessments   []Assessment `json:"assessments"`

	// Checkpoints Sealed checkpoints in the independently verified dependency-closed frontier.
	Checkpoints []Checkpoint `json:"checkpoints"`

	// ExecutionID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	ExecutionID *Digest `json:"executionID,omitempty"`

	// ExecutionStatus Application control-plane lifecycle state. It is deliberately excluded from canonical semantic identity.
	ExecutionStatus *ExecutionExecutionStatus `json:"executionStatus,omitempty"`

	// Failure A deterministic semantic rejection. Its presence does not make the HTTP
	// response an error: the run produced a real answer, and every artifact
	// verified before the rejection is retained.
	Failure *SemanticFailure `json:"failure,omitempty"`

	// FinalStateDigest A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	FinalStateDigest *Digest `json:"finalStateDigest,omitempty"`

	// InputID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	InputID *Digest `json:"inputID,omitempty"`

	// JournalPrefixDigest A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	JournalPrefixDigest *Digest `json:"journalPrefixDigest,omitempty"`

	// PlanID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	PlanID Digest `json:"planID"`

	// SemanticRunID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	SemanticRunID *Digest              `json:"semanticRunID,omitempty"`
	SpineStatus   ExecutionSpineStatus `json:"spineStatus"`

	// WorldID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	WorldID *Digest `json:"worldID,omitempty"`
}

// ExecutionExecutionStatus Application control-plane lifecycle state. It is deliberately excluded from canonical semantic identity.
type ExecutionExecutionStatus string

// ExecutionSpineStatus defines model for Execution.SpineStatus.
type ExecutionSpineStatus string

// ExecutorIdentity The executing backend. It affects only `executionID` and never enters checkpoint or journal identity.
type ExecutorIdentity struct {
	Backend string `json:"backend"`

	// Version A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	Version Digest `json:"version"`
}

// FieldCopy defines model for FieldCopy.
type FieldCopy struct {
	// Destination A field path of the form kind.field.
	Destination string `json:"destination"`

	// Source A field path of the form kind.field.
	Source string `json:"source"`
}

// FieldDeclaration defines model for FieldDeclaration.
type FieldDeclaration struct {
	// Kind The closed typed-value vocabulary.
	Kind ValueKind `json:"kind"`
	Name string    `json:"name"`

	// RequiredAtConstruction Whether state construction rejects an entity of this kind that omits
	// the field. This is a representation obligation, independent of the
	// value type; rule-level presence obligations are enforced by the
	// transformations that read the field, not here.
	RequiredAtConstruction *bool `json:"requiredAtConstruction,omitempty"`
}

// FieldReduction defines model for FieldReduction.
type FieldReduction struct {
	Destination string             `json:"destination"`
	Kind        FieldReductionKind `json:"kind"`
	Source      string             `json:"source"`
}

// FieldReductionKind defines model for FieldReduction.Kind.
type FieldReductionKind string

// FormRelatedEntity The closed related-entity transformation payload.
type FormRelatedEntity struct {
	CopiedFields  *[]FieldCopy         `json:"copiedFields,omitempty"`
	GroupingField string               `json:"groupingField"`
	OutputKey     *OutputKeyExpression `json:"outputKey,omitempty"`
	OutputKind    string               `json:"outputKind"`
	OutputSlot    string               `json:"outputSlot"`
	RelationKind  string               `json:"relationKind"`
	SourceCount   int64                `json:"sourceCount"`
	SourceKind    string               `json:"sourceKind"`
	Sources       []SourceReference    `json:"sources"`
}

// InputLineage Pins the observation load that produced the initial state. Entity identities are derived from it, so a different lineage is a different input.
type InputLineage struct {
	Namespace string `json:"namespace"`
	RootKey   string `json:"rootKey"`
}

// OutputKeyExpression defines model for OutputKeyExpression.
type OutputKeyExpression struct {
	Field string                  `json:"field"`
	Kind  OutputKeyExpressionKind `json:"kind"`
}

// OutputKeyExpressionKind defines model for OutputKeyExpression.Kind.
type OutputKeyExpressionKind string

// OutputSlotReference defines model for OutputSlotReference.
type OutputSlotReference struct {
	Rule string `json:"rule"`
	Slot string `json:"slot"`
}

// Plan defines model for Plan.
type Plan struct {
	Checkpoints []CheckpointDeclaration `json:"checkpoints"`

	// Declarations The declarations as the compiler accepted them, in canonical order.
	//
	// Present on retrieval and omitted on creation, because a client that
	// just submitted declarations already holds them. This is projected
	// from the compiled plan rather than from a stored copy of the
	// request, so it shows what was compiled rather than what was sent;
	// where the two differ, the difference is the compiler's
	// canonicalization and is usually the answer being looked for.
	//
	// Operational telemetry cannot carry declarations: trace attributes
	// are limited to three identities plus closed tokens, and metrics to
	// bounded enums. This projection is therefore the only way to resolve
	// a PlanID observed in a trace back to what the plan actually says.
	Declarations *PlanDeclarations `json:"declarations,omitempty"`

	// PlanID A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	PlanID   Digest            `json:"planID"`
	Profiles []CompiledProfile `json:"profiles"`

	// Rules Compiled rule identities in dependency order.
	Rules []string `json:"rules"`
}

// PlanDeclarations defines model for PlanDeclarations.
type PlanDeclarations struct {
	// CompilerSemanticsVersion The pinned compiler semantics version. Compilation is reproducible only against a fixed version.
	CompilerSemanticsVersion string                `json:"compilerSemanticsVersion"`
	Profiles                 *[]ProfileDeclaration `json:"profiles,omitempty"`
	Rules                    RulesetDeclaration    `json:"rules"`

	// Schema Declaration order is not semantic; the compiler canonicalizes it.
	Schema SchemaDeclaration `json:"schema"`
}

// Problem An RFC 9457 problem document. It never carries payloads, entity references, evidence, or internal error text.
type Problem struct {
	// Code A stable closed code token, when one classifies the problem.
	Code *string `json:"code,omitempty"`

	// Detail Fixed safe text. Never contains request payloads or dependency errors.
	Detail *string `json:"detail,omitempty"`

	// Diagnostics Closed compiler diagnostic codes, present only for a compilation failure.
	Diagnostics *[]CompilerDiagnostic `json:"diagnostics,omitempty"`
	Status      int32                 `json:"status"`

	// Title A short, stable, human-readable summary. Not a diagnostic payload.
	Title string `json:"title"`

	// Type A stable problem-type URI from the closed Maiden Lane vocabulary.
	Type string `json:"type"`
}

// ProfileDeclaration A closed consumer-completeness declaration. Ordering between profiles is proved from normalized implication, never from names.
type ProfileDeclaration struct {
	Aggregation  ProfileDeclarationAggregation `json:"aggregation"`
	Implies      *[]string                     `json:"implies,omitempty"`
	Key          string                        `json:"key"`
	Requirements []RequirementAtom             `json:"requirements"`
	Scope        struct {
		EntityKind string                      `json:"entityKind"`
		Kind       ProfileDeclarationScopeKind `json:"kind"`
	} `json:"scope"`
}

// ProfileDeclarationAggregation defines model for ProfileDeclaration.Aggregation.
type ProfileDeclarationAggregation string

// ProfileDeclarationScopeKind defines model for ProfileDeclaration.Scope.Kind.
type ProfileDeclarationScopeKind string

// ReadinessVerdict A readiness answer. `needs_input` is a successful assessment, not a failure.
type ReadinessVerdict string

// RelationDeclaration defines model for RelationDeclaration.
type RelationDeclaration struct {
	FromKind string `json:"fromKind"`
	Kind     string `json:"kind"`
	ToKind   string `json:"toKind"`
}

// RelationInput defines model for RelationInput.
type RelationInput struct {
	FromKind      string `json:"fromKind"`
	FromSourceKey string `json:"fromSourceKey"`
	Kind          string `json:"kind"`
	ToKind        string `json:"toKind"`
	ToSourceKey   string `json:"toSourceKey"`
}

// RequirementAtom defines model for RequirementAtom.
type RequirementAtom struct {
	// Code A closed readiness requirement code.
	Code  string              `json:"code"`
	Field string              `json:"field"`
	Kind  RequirementAtomKind `json:"kind"`
}

// RequirementAtomKind defines model for RequirementAtom.Kind.
type RequirementAtomKind string

// RulesetDeclaration defines model for RulesetDeclaration.
type RulesetDeclaration struct {
	Checkpoints     *[]CheckpointDeclaration    `json:"checkpoints,omitempty"`
	Transformations []TransformationDeclaration `json:"transformations"`
}

// SchemaDeclaration Declaration order is not semantic; the compiler canonicalizes it.
type SchemaDeclaration struct {
	Entities  []EntityDeclaration    `json:"entities"`
	Relations *[]RelationDeclaration `json:"relations,omitempty"`
}

// SemanticFailure A deterministic semantic rejection. Its presence does not make the HTTP
// response an error: the run produced a real answer, and every artifact
// verified before the rejection is retained.
type SemanticFailure struct {
	// Code The closed invariant, operation-invariant, or integrity code.
	//
	// The rejected rule is deliberately not reported here. A failure
	// report is a canonical semantic artifact and does not carry a rule
	// identity; the accepted rule list plus the closed code identify the
	// boundary that refused, without inventing a field the kernel cannot
	// populate truthfully.
	Code *string             `json:"code,omitempty"`
	Kind SemanticFailureKind `json:"kind"`
}

// SemanticFailureKind defines model for SemanticFailure.Kind.
type SemanticFailureKind string

// SourceReference defines model for SourceReference.
type SourceReference struct {
	CanonicalSourceKey string `json:"canonicalSourceKey"`
	Kind               string `json:"kind"`
}

// StateInput defines model for StateInput.
type StateInput struct {
	Entities []EntityInput `json:"entities"`

	// Lineage Pins the observation load that produced the initial state. Entity identities are derived from it, so a different lineage is a different input.
	Lineage   InputLineage     `json:"lineage"`
	Relations *[]RelationInput `json:"relations,omitempty"`
}

// TransformationDeclaration A closed tagged union. Exactly one payload must be present and must agree with `operator`.
type TransformationDeclaration struct {
	After *[]string `json:"after,omitempty"`

	// Aggregate The closed related-field aggregation payload.
	Aggregate      *AggregateRelatedFields `json:"aggregate,omitempty"`
	DeclaredReads  *[]string               `json:"declaredReads,omitempty"`
	DeclaredWrites *[]string               `json:"declaredWrites,omitempty"`

	// Form The closed related-entity transformation payload.
	Form     *FormRelatedEntity                `json:"form,omitempty"`
	Id       string                            `json:"id"`
	Operator TransformationDeclarationOperator `json:"operator"`
}

// TransformationDeclarationOperator defines model for TransformationDeclaration.Operator.
type TransformationDeclarationOperator string

// Value One typed scalar value. Exactly one of the payload fields must match `kind`.
type Value struct {
	// Atom Present when kind is atom.
	Atom *string `json:"atom,omitempty"`

	// Int64 Present when kind is int64.
	Int64 *int64 `json:"int64,omitempty"`

	// Kind The closed typed-value vocabulary.
	Kind ValueKind `json:"kind"`

	// String Present when kind is string. Exact UTF-8 bytes, never normalized.
	String *string `json:"string,omitempty"`
}

// ValueKind The closed typed-value vocabulary.
type ValueKind string

// WorldInput The pinned execution world. An empty reference list is a real, versioned empty world, not a missing value.
type WorldInput struct {
	References *[]WorldReference `json:"references,omitempty"`
}

// WorldReference defines model for WorldReference.
type WorldReference struct {
	// ContentDigest A content identity produced by the semantic kernel, rendered as sha256:<64 lowercase hex>. Clients must treat it as opaque and must never recompute it.
	ContentDigest Digest             `json:"contentDigest"`
	Kind          WorldReferenceKind `json:"kind"`
}

// WorldReferenceKind defines model for WorldReference.Kind.
type WorldReferenceKind string

// TenantHeader defines model for TenantHeader.
type TenantHeader = string

// BadRequest An RFC 9457 problem document. It never carries payloads, entity references, evidence, or internal error text.
type BadRequest = Problem

// DependencyUnavailable An RFC 9457 problem document. It never carries payloads, entity references, evidence, or internal error text.
type DependencyUnavailable = Problem

// InternalError An RFC 9457 problem document. It never carries payloads, entity references, evidence, or internal error text.
type InternalError = Problem

// MethodNotAllowed An RFC 9457 problem document. It never carries payloads, entity references, evidence, or internal error text.
type MethodNotAllowed = Problem

// NotFound An RFC 9457 problem document. It never carries payloads, entity references, evidence, or internal error text.
type NotFound = Problem

// UnprocessableEntity An RFC 9457 problem document. It never carries payloads, entity references, evidence, or internal error text.
type UnprocessableEntity = Problem

// UnsupportedMediaType An RFC 9457 problem document. It never carries payloads, entity references, evidence, or internal error text.
type UnsupportedMediaType = Problem

// CreateExecutionParams defines parameters for CreateExecution.
type CreateExecutionParams struct {
	// XMaidenLaneTenant The tenant that owns every artifact touched by this request. Scoping is
	// mandatory; an identifier from another tenant is reported as absent.
	XMaidenLaneTenant TenantHeader `json:"X-Maiden-Lane-Tenant"`
}

// CreatePlanParams defines parameters for CreatePlan.
type CreatePlanParams struct {
	// XMaidenLaneTenant The tenant that owns every artifact touched by this request. Scoping is
	// mandatory; an identifier from another tenant is reported as absent.
	XMaidenLaneTenant TenantHeader `json:"X-Maiden-Lane-Tenant"`
}

// GetPlanParams defines parameters for GetPlan.
type GetPlanParams struct {
	// XMaidenLaneTenant The tenant that owns every artifact touched by this request. Scoping is
	// mandatory; an identifier from another tenant is reported as absent.
	XMaidenLaneTenant TenantHeader `json:"X-Maiden-Lane-Tenant"`
}

// CreateExecutionJSONRequestBody defines body for CreateExecution for application/json ContentType.
type CreateExecutionJSONRequestBody = CreateExecutionRequest

// CreatePlanJSONRequestBody defines body for CreatePlan for application/json ContentType.
type CreatePlanJSONRequestBody = PlanDeclarations

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Report process liveness
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// GetReadiness Report process readiness
	// (GET /readyz)
	GetReadiness(w http.ResponseWriter, r *http.Request)
	// CreateExecution Execute a compiled plan
	// (POST /v1/executions)
	CreateExecution(w http.ResponseWriter, r *http.Request, params CreateExecutionParams)
	// CreatePlan Compile declarations into a semantic plan
	// (POST /v1/plans)
	CreatePlan(w http.ResponseWriter, r *http.Request, params CreatePlanParams)
	// GetPlan Retrieve a compiled plan
	// (GET /v1/plans/{planID})
	GetPlan(w http.ResponseWriter, r *http.Request, planID Digest, params GetPlanParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GetHealth Report process liveness
// (GET /healthz)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetReadiness Report process readiness
// (GET /readyz)
func (_ Unimplemented) GetReadiness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateExecution Execute a compiled plan
// (POST /v1/executions)
func (_ Unimplemented) CreateExecution(w http.ResponseWriter, r *http.Request, params CreateExecutionParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreatePlan Compile declarations into a semantic plan
// (POST /v1/plans)
func (_ Unimplemented) CreatePlan(w http.ResponseWriter, r *http.Request, params CreatePlanParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetPlan Retrieve a compiled plan
// (GET /v1/plans/{planID})
func (_ Unimplemented) GetPlan(w http.ResponseWriter, r *http.Request, planID Digest, params GetPlanParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateExecution operation middleware
func (siw *ServerInterfaceWrapper) CreateExecution(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateExecutionParams

	headers := r.Header

	// ------------- Required header parameter "X-Maiden-Lane-Tenant" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Maiden-Lane-Tenant")]; found {
		var XMaidenLaneTenant TenantHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Maiden-Lane-Tenant", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Maiden-Lane-Tenant", valueList[0], &XMaidenLaneTenant, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Maiden-Lane-Tenant", Err: err})
			return
		}

		params.XMaidenLaneTenant = XMaidenLaneTenant

	} else {
		err := fmt.Errorf("Header parameter X-Maiden-Lane-Tenant is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Maiden-Lane-Tenant", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateExecution(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePlan operation middleware
func (siw *ServerInterfaceWrapper) CreatePlan(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreatePlanParams

	headers := r.Header

	// ------------- Required header parameter "X-Maiden-Lane-Tenant" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Maiden-Lane-Tenant")]; found {
		var XMaidenLaneTenant TenantHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Maiden-Lane-Tenant", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Maiden-Lane-Tenant", valueList[0], &XMaidenLaneTenant, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Maiden-Lane-Tenant", Err: err})
			return
		}

		params.XMaidenLaneTenant = XMaidenLaneTenant

	} else {
		err := fmt.Errorf("Header parameter X-Maiden-Lane-Tenant is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Maiden-Lane-Tenant", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePlan(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlan operation middleware
func (siw *ServerInterfaceWrapper) GetPlan(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "planID" -------------
	var planID Digest

	err = runtime.BindStyledParameterWithOptions("simple", "planID", chi.URLParam(r, "planID"), &planID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "planID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPlanParams

	headers := r.Header

	// ------------- Required header parameter "X-Maiden-Lane-Tenant" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Maiden-Lane-Tenant")]; found {
		var XMaidenLaneTenant TenantHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Maiden-Lane-Tenant", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Maiden-Lane-Tenant", valueList[0], &XMaidenLaneTenant, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Maiden-Lane-Tenant", Err: err})
			return
		}

		params.XMaidenLaneTenant = XMaidenLaneTenant

	} else {
		err := fmt.Errorf("Header parameter X-Maiden-Lane-Tenant is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Maiden-Lane-Tenant", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlan(w, r, planID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadiness)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/plans", wrapper.CreatePlan)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/plans/{planID}", wrapper.GetPlan)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/executions", wrapper.CreateExecution)
	})

	return r
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type DependencyUnavailableApplicationProblemPlusJSONResponse Problem

type InternalErrorApplicationProblemPlusJSONResponse Problem

type MethodNotAllowedApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type UnprocessableEntityApplicationProblemPlusJSONResponse Problem

type UnsupportedMediaTypeApplicationProblemPlusJSONResponse Problem

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth204Response struct {
}

func (response GetHealth204Response) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetHealth405ApplicationProblemPlusJSONResponse struct {
	MethodNotAllowedApplicationProblemPlusJSONResponse
}

func (response GetHealth405ApplicationProblemPlusJSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(405)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness204Response struct {
}

func (response GetReadiness204Response) VisitGetReadinessResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetReadiness405ApplicationProblemPlusJSONResponse struct {
	MethodNotAllowedApplicationProblemPlusJSONResponse
}

func (response GetReadiness405ApplicationProblemPlusJSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(405)
	_, err := buf.WriteTo(w)
	return err
}

type CreateExecutionRequestObject struct {
	Params CreateExecutionParams
	Body   *CreateExecutionJSONRequestBody
}

type CreateExecutionResponseObject interface {
	VisitCreateExecutionResponse(w http.ResponseWriter) error
}

type CreateExecution200JSONResponse Execution

func (response CreateExecution200JSONResponse) VisitCreateExecutionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateExecution400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response CreateExecution400ApplicationProblemPlusJSONResponse) VisitCreateExecutionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateExecution404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response CreateExecution404ApplicationProblemPlusJSONResponse) VisitCreateExecutionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateExecution405ApplicationProblemPlusJSONResponse struct {
	MethodNotAllowedApplicationProblemPlusJSONResponse
}

func (response CreateExecution405ApplicationProblemPlusJSONResponse) VisitCreateExecutionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(405)
	_, err := buf.WriteTo(w)
	return err
}

type CreateExecution415ApplicationProblemPlusJSONResponse struct {
	UnsupportedMediaTypeApplicationProblemPlusJSONResponse
}

func (response CreateExecution415ApplicationProblemPlusJSONResponse) VisitCreateExecutionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type CreateExecution422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response CreateExecution422ApplicationProblemPlusJSONResponse) VisitCreateExecutionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CreateExecution500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response CreateExecution500ApplicationProblemPlusJSONResponse) VisitCreateExecutionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateExecution503ApplicationProblemPlusJSONResponse struct {
	DependencyUnavailableApplicationProblemPlusJSONResponse
}

func (response CreateExecution503ApplicationProblemPlusJSONResponse) VisitCreateExecutionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlanRequestObject struct {
	Params CreatePlanParams
	Body   *CreatePlanJSONRequestBody
}

type CreatePlanResponseObject interface {
	VisitCreatePlanResponse(w http.ResponseWriter) error
}

type CreatePlan201JSONResponse Plan

func (response CreatePlan201JSONResponse) VisitCreatePlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlan400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response CreatePlan400ApplicationProblemPlusJSONResponse) VisitCreatePlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlan405ApplicationProblemPlusJSONResponse struct {
	MethodNotAllowedApplicationProblemPlusJSONResponse
}

func (response CreatePlan405ApplicationProblemPlusJSONResponse) VisitCreatePlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(405)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlan415ApplicationProblemPlusJSONResponse struct {
	UnsupportedMediaTypeApplicationProblemPlusJSONResponse
}

func (response CreatePlan415ApplicationProblemPlusJSONResponse) VisitCreatePlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlan422ApplicationProblemPlusJSONResponse struct {
	UnprocessableEntityApplicationProblemPlusJSONResponse
}

func (response CreatePlan422ApplicationProblemPlusJSONResponse) VisitCreatePlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlan500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response CreatePlan500ApplicationProblemPlusJSONResponse) VisitCreatePlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlanRequestObject struct {
	PlanID Digest `json:"planID"`
	Params GetPlanParams
}

type GetPlanResponseObject interface {
	VisitGetPlanResponse(w http.ResponseWriter) error
}

type GetPlan200JSONResponse Plan

func (response GetPlan200JSONResponse) VisitGetPlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlan400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response GetPlan400ApplicationProblemPlusJSONResponse) VisitGetPlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlan404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetPlan404ApplicationProblemPlusJSONResponse) VisitGetPlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlan405ApplicationProblemPlusJSONResponse struct {
	MethodNotAllowedApplicationProblemPlusJSONResponse
}

func (response GetPlan405ApplicationProblemPlusJSONResponse) VisitGetPlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(405)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlan500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response GetPlan500ApplicationProblemPlusJSONResponse) VisitGetPlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Report process liveness
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// GetReadiness Report process readiness
	// (GET /readyz)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)
	// CreateExecution Execute a compiled plan
	// (POST /v1/executions)
	CreateExecution(ctx context.Context, request CreateExecutionRequestObject) (CreateExecutionResponseObject, error)
	// CreatePlan Compile declarations into a semantic plan
	// (POST /v1/plans)
	CreatePlan(ctx context.Context, request CreatePlanRequestObject) (CreatePlanResponseObject, error)
	// GetPlan Retrieve a compiled plan
	// (GET /v1/plans/{planID})
	GetPlan(ctx context.Context, request GetPlanRequestObject) (GetPlanResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(w http.ResponseWriter, r *http.Request) {
	var request GetReadinessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx, request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		if err := validResponse.VisitGetReadinessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateExecution operation middleware
func (sh *strictHandler) CreateExecution(w http.ResponseWriter, r *http.Request, params CreateExecutionParams) {
	var request CreateExecutionRequestObject

	request.Params = params

	var body CreateExecutionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateExecution(ctx, request.(CreateExecutionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateExecution")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateExecutionResponseObject); ok {
		if err := validResponse.VisitCreateExecutionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePlan operation middleware
func (sh *strictHandler) CreatePlan(w http.ResponseWriter, r *http.Request, params CreatePlanParams) {
	var request CreatePlanRequestObject

	request.Params = params

	var body CreatePlanJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePlan(ctx, request.(CreatePlanRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePlan")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePlanResponseObject); ok {
		if err := validResponse.VisitCreatePlanResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPlan operation middleware
func (sh *strictHandler) GetPlan(w http.ResponseWriter, r *http.Request, planID Digest, params GetPlanParams) {
	var request GetPlanRequestObject

	request.PlanID = planID
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPlan(ctx, request.(GetPlanRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPlan")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPlanResponseObject); ok {
		if err := validResponse.VisitGetPlanResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5Dxpcxs3ln8F1TufdpuU7CjZifJJI9ETlWVJRcnOToVeEup+JBGhgQ6ApsS49N+38AD0xebRcpJJ1fqL",
	"KRLHw7sv4EuUyCyXAoTR0emXKKeKZmBA4V/3IKgwPwJNQdm/U9CJYrlhUkSn0f0SiMERxCypIfJJaAIr",
	"UGtClWFzmhhiZJEsISUPa2KWTBMFvxagzZDcJTJnYkGYnoiMipQaqdY/ECoIS0EYNmegyFzJjFAhzRJU",
	"2AoXyaUykBKqCX3QIMxwIqI4YhaqpYM2jgTNIDqN/mfwgdolB1dUwMCdKIojCwhTkEanRhUQRzpZQkbt",
	"ITP6fAViYZbR6Zu3f4+jjIny7zjKqTGg7Eb/+zMd/HY8+P6z/3/w+T//FsWRWed2W20UE4vo5eXF7qVz",
	"KTQgTv9B07FDgv0rkcKAwI80zzlLqEXuUa7kA4fsv37RFtNfatD9TcE8Oo3+46ii25H7VR/dullu001a",
	"edyTJ6pJRvlcqgxSIhUxFSEd9nCIx2z0EkcXkINIQSTrj4KuKOP0gcOfCf4ZCfQiaQkLQllUAA1J/ZQZ",
	"XZMH+6dRDFI8xqWwpKN8pJRUfyr4gjC/N8losmTCCgkTiRSaaYOHkUlSKOUh/QBmKdNrac44l0+WS/9s",
	"VtGyUAmQVIImQhqii9wKHfKKRzGkJEM4EeRrad7JQvypoF5LootkWakbeGbaaDJHpmbaczXC91HkSiag",
	"tWWVkTDMrP+dAvgEnBMvgg+Fw2sKCacKAdBWLhMqpGAJ5YSJvDB6Ip5A2WV+gcRAOiTnMssZxwlkThkv",
	"FGiSUKWstgWmSMroQkhtWEISmYK2ehJx4ckJ6QdIGb1HnfXvQcaDTJ0kWy6r72p3G0Z2sl/Rbni2WChY",
	"UAO3ClI7EuGmacrsHMpvlcxBGWZ17ZxyDXGU1776Es0Z8BQ/MQMZfmhp7FKFU6Xo2v79yBxbgyiy6PRn",
	"NJkcDExNkXOwpkaKqbBgsRVMGdoX+LWgfIq7TWmipNZTJ1I6iiMOWk+lmtYG6ejzpu2om6mfHRhxtDFc",
	"Plh+sICW2BkDpwbSd+Vhd2JokzgJlxpSotwyA9ySUL+65bacrrmk6TBq45eKZOmU6y7eQMDOZY7ozQMp",
	"m2TZNb+DDTropiAtEpSmgxdGwMZhXveiTuDee6bY4J5Asjsk9z2ySC92U6ALbm7/KKw4NtwKvqFqAWbf",
	"VjeFyQtzx6UZwxwUiAQ2+NWv1EJZA4BubMWBizp5XGvQOgtq6nDJp+XEy4t9x7tgC+ugvcRRsoTkMZdM",
	"mDNvZPrMTt2ng8dnTGsmFmOHlCx45U0BPQ/CWQ5yyt154Wgi0GJTw/Tc+j5klOVmTZ6WIIgCmq6t2B7O",
	"j7mSc8ahz7n9lPew7txhBSplyV68jIGmTIDWn/z4Noc1SFpiewvR6gdpQFjB08Vv5+VaPfnt6zinmv26",
	"WdtQ35cjtaEGLnpNahGpCVPrZFtpVdKyDsBu+lxU7lNf1TA32wJcVXAgT0upgXizb80fOpcV5GQurZ+u",
	"h5vxXxw9dlKibdsRNQ6OzlOipwfprWPbnud73MIMvSW7E+pqlR2Qq4vSFe0rRzKFTdqcBR8lqfnALXfX",
	"kiP4bB+v31/f/HQ9fXc5urL89fH67uPt7c34fnQxvbkdjc/ub8ZRHF2Mzq/OxqOL6dn5+ejubvrh8u7D",
	"2f35j1Ec/TS+vB9Nz2+u311dnt9PP16PR3c3V59GFzjtdnR9Mbo+/9f0/F/nV6Mojm7HN+8ur0bTm/HF",
	"aDz9eH07vvl09o+r0X4/Dw/ciUoF1MDoGZLCHreWRuiBTsDpUl1imsUFQbtIP2qPf4kjJphhlN8Z73/v",
	"mo+DLm38ghzHqehpSFY2hkvgVnKWrBtu+JKKBejh6k0HTuPoSSqe7tvpJzvIQ9cigwe1ddp4E4EdUHZR",
	"r1KiG5zswi6f+TJrkiuZFklImwHRkFFhufoRlAAeEwUiBeUyYHpJ33773emkOD7+JvnuhHD5BCqhGsgS",
	"nvFbGJJzzuy5SVZoQ4zlI8KMnS1z+msBhIrU/SZgBYoosLgqDBBmUIqeaYZ+bOR3O/7Kf1Ejk+YX/fl4",
	"8D0dzD9/+e7k5W9dqtSF7a/X8x3B395goL7bjtjwa0M3dzTHif3itRsBxLPoAI0lcVzk0mEJEh7TN5yB",
	"JszoWl7BZ3keYR1PBAbgws8umfE0fLKzqQKSgmKrijcdS7pUrVnCRHAmgC6AaOkcUhpgSChuwcTK/iUV",
	"SSTnLAUiBbgEbkvxBzBdbLDNo5nvCXJ30/gT5UU9TKoo0ouyHbDuJndQ4n09lSSB3EA6Ljh0hQYyy5gx",
	"kBKjqNDMpZKYIGEekSoFNSRjzCHhr07iaZ4DVWQJCvpFB5UP3iNQrWK4jhUrv6rjhHdAubX61Rh7PMuI",
	"TITUsOFrsgLFbPBTyxcPvMcwV1IYBqpxzl3g1kKADnAhkLKPXSsnWatSdJzzrMqEoX1Qkg+sRQLC2RyS",
	"dcKBoLQPySUWRVLg7AEUNcDXBJ4TXqTurFld3oMhCdJdd5EsniyR40gVQrhPukgSgBRQe1HrgXbaWp98",
	"3OsL+O3f+eEovcKb1ouekQnmRPvg/BdZKJQxmLPnvrv1dVwCpsdFv2k5E1DxRCBNBxksAlaUs3RqQdvu",
	"Ab3auS/9nzpMTelsSv92Pdf0NnvmIr2oiAV5oMkjiBQ5ns7nkBhNpOBrMqvJ4Ax9GafUQBhQjUBNKuLZ",
	"oCECTSXr93H10G3lvmF3vQ+TCdor9ldgPexdrdOF1ip/2s98pKANE6Xr1HZEXZ43p2ZJ5ByV6lyqjFgb",
	"N8TfOgNc50T8Xuu18OEXjxugb0XJ613DYO33+gqYt3wJ5eUd+d8zcy6FNsqnkhE9c1pws4XXf1oC1rmd",
	"D5fU5vqKj655Z4hOphGVvvqeMaMnApGMqCX3dgDThBIFuQINwjh7Ih84c3n8uG41PY0mVq0UQOzBfsD8",
	"x4DDCjhxayRQm+88QhBzqapwZSLQ+bCk9oMQQAU0JSV4MeYo0d1A18+j8UFKDlRssAFi2/tkW6lf5e2/",
	"Sio2Mzit+g/WFbDQ893JNKPPncq3koqDHMjD+VyqzJd3Rq9Vqa3yjuepJtW2l3gSmbN6benwWCpUfNou",
	"1ELJImdigYM6SSCx3uBDgP2FifewHj1bftU+bPPztxU9ZFnO2CLSe2o+jnrnsnBZYofE6DRCFomwh4Rl",
	"lnmOy8MzYWAB6oCKTKgbHopqF4LU6jJthHeq2EZxxpr2GsoaCGqTq3n6FrK6OBiD3CsXJfZk3luG2sSq",
	"IA1q5RjVcqlTMWXexMUDGBMHL3nUCGvbwSz6yczENmqlJGVzRJ4hIZhFNVp9jb7npmRYLaVzmmwxDFJu",
	"Sct3KDu3TDWpC5FdvP6KhMhBOi+RWSaFr2G7knW/ivWOEzTLiP1OYO1Tt9R0C3MLQpzuB3cBeGt969fW",
	"fQ4X2e4iRoemrLeI7G3A4FRc1Me/Lv86Z7yH8mkXKrrq21tzFzjTlVxqcspEvenLJTB6pCi2hTUOjHZA",
	"Ux54GzdctCjQq5LhSiEhDNafqlBh00jnTIiyvmH9wjCL+Mig2f/j+iJRAbIHDi4wogvKhDaEkjl7hrSc",
	"2eXG9ya1J/Eeji2pvbPSawdBm/kP6zO6w/8bUzcKKlvwXm4RwOwkuu9j6mepzgQZvzsn3598+9/E90+R",
	"VCaFDZUxgHURakKVsjzunS0dBwdfBX1ov1pZaUggtuFr2UgISklFDDybLhetu2amDbW8UZbOUiBGPoKI",
	"XXOAFPY3qjWbM3CG1sPeyTEpGMr45j7vkNc0nYMDj1y7s0phLDuWrV/h0PZYNQnHg3XXUqsC3/a+iFJg",
	"2s1vsY9gjJONuVSENsqHPot1eF5ws7TZ1W9TZnPqbuE3b61bSJ+dW/jt99/XnMQ3x51uomGGd1N1KZV1",
	"XZC4MVkWGRUDG24hsXWRZVSth+RaGnRiSqzUPPwtOnQrB3m2GNhh5OP4ssz/B95yTdfkigogK5nQh4Jb",
	"IBq1pKUxuT49OspcgzanAoYyNyyjPF0LmrFEDxOZhf5DfeQzXpgItX5FwGeh2N5EAv4akFhSZYvAt/Va",
	"T9mvBEzoIgM1CB2DArSut3kOyY01Z5jcAvMEIEhQw1ahY13RO6fCHpaz3yAlLCtzw7HXI26I9Rs7WvKq",
	"vr26R0c5n2rg2EraGcHiNtC3V3JLlUa1WpoOErBaH9SZkVmndCUy7+szOhW7Nd5qu74WUcEZmcr5tJWE",
	"2O371vba5LXOdgp3orhBthb+urh2o1mqQ3hVGEOo0E+ghmQmAFI9xXhm5qIczDVrPS84qbK7Ll1D6yqy",
	"yobQ1MJdW6mTncY+LvyK8q2S2V6qbXKofN+rRhs2KWd2Y9sd5rCCbY9j2B931zv7H9T+tGvNvYhoAlXu",
	"1Fy3G01NAf5dO38qbm63QnZatMNjXde17Z2FA/t14v3BboeT+xeKLFs524M3uG/M27lJ2yK3duzC2aZz",
	"388U12a6yNHqOOyO9bHAD85pCT5jWSplv2GzxKY1DZbgYARtNq3s6CrvYxt5b4yXsHeiulWc7evzpGBA",
	"WR8Wfcuy0qxCp4GNenRVRChvFmX0EZAIP97f305EuCyHxQ4bCZy6O0eFqNJ71Mo+90YsxoJf897hRJT1",
	"/weYSwX+3pIHxQXLNhiBtLPzpFPx1DLn1hFVjFq7aOch9gf1L12ctlA2lEONNBETcb+sLu/4LEerbm/x",
	"Ud5uxOIIOQs216IGr2Chle6o6Ze3oCw+SvS660AU95uIUPR0bF92hSAwnNmYjBe67sdjjOivZPrqzoMs",
	"RErxjhGWdeaFhjQmT8wsZRH6e6xLS30BsNYm5HqAJiKXecGpAWJUYZbzgvN1ow60XTnnShrE4LTE97Qs",
	"iQcUTEvsT7d2LXRZvU65aKXTe+rsw5qYvrbZqBPwqvPyFf5xfxVXNnm2lRuvcv27VmnUBb5KJ26BpIXN",
	"AFa8Wy9uN3CvjAoNXSwgJYVApTh6ponha8y9+IDcdWI+QJmvKLsz6UIBoKSRmVM8Us06Ir7Qz96jjSvc",
	"HTr4klHzjlmZm4bURiI9o8Yw9SfFTN+I05Jmb/Vxo2hq49sttUCP14ZHKFU29eXSadn2W+Ks/OnQq3wM",
	"a2phoy6uc32J/TtB7UIp0QnlVBEs5DdZzPdhBE5zADvmyqhJlmRmlUwXT3n/vVWQ8xyK6UNsRrDWycju",
	"hKErhx62CI4d1rM8oZi6mRnr3bzhQToMEjfYo5F8vH83+Dt5WBvQIflSpWb297NsNTMVfLscDyTvwDVo",
	"tNJqoVXM7Rs7ggWcdwXktd73/i0EvjpRNl4RbDYbkjNBAG+blQls51f4PhTK41CEsLPdvTQ7MyQY/A04",
	"z7obXFilxQ82CnjM3dXwDWK05vQNW7Gdv2+HYdvR0YLmeokF90SKOVsUqt0VssdNaMDRkX1CiZzLboaz",
	"3jjRhZrTBAg+TYB9tSzLOQbart2nlub1Lq51aX2dwxId3czCLKViBu9HkyemwLW00sQMyT8l0aCsGFnw",
	"sCo/EQsQ6BKXhfkfCMPlnMC1fv6nrF1wcM8+lCMmwmem63ClTIHViAjyCCOH2dHqzaxy5kn5eADBfFyK",
	"Ntgj2Z1q1vWyyGwi3BMaQ3JWmKU1FUm5YAoczUVKjPQX/nMu1wiS/f6JrlGAqijmAbgUCysPRu55CGV2",
	"cnwyCxppdnL8zSwOLfjW3cZMHkbB89YjKwpWQDkGC0v02h/QizfavaZgBQDxdMZ9zUmTQkNV3Zpteypg",
	"FhMmEl6kdtXyDRQXQyhZGBuMGw18HgI7fWpBKwQaIvCNgwpMoYTVHjMhzWBug49ZWVKjIp0InFS+aOAf",
	"pahPdN8M7HzqHtQoV/AdHzV+qW4rkBQw/HGxpQ/DnPclval1mNkW+8rCJDKDkHOoIlqXSLVHDNHMRJTh",
	"DLIabaVmq2SXv6yK7Su1XG2J4InwcRkGi0/2c0hxFL4BMAMa3szxRaWoXq85u72s9Z+eRsfDN8Nj7xoJ",
	"mrPoNPoGv8JLPEtUekdLoNwsf7Of/f3xUpgu0+g0+ieYH3FI1HoQ5+3xSbcGqoPk3+5AM8LZCvBJj5Pj",
	"b7ep13KHo42nVPBFCVcTi06jsUNTWN+ubbFsMUMX2mpTd7Dos513hMnunYcs8/BfdU7LfS46D9VS/Ucd",
	"WdUA7jzz6s1RaebdI1Gy6x6ba/W2GtzGLSsmC83XIbOWkpxTQSReNQnOQ6NDy4my9wU0UG61hpO8EB3U",
	"G7lRRpxSQ+0SpKMQKaiJcBOrzV1RDaX18vp+NL78QC5Gny7P7i9vrl2C6Ue2WA6usNH1AjRbCKJzSEIh",
	"HIWI6cpATETQL7O3x2/Jmc+kuO5zL4C64Ma1mblXiFbWM4ecumTPkNyjbtZLmkNlWqj1hx5BkcyqHkzl",
	"FMoVco1UdAFWxzM0BHJOnpYsWU6Ef/dmDcYrfetAB0vtZB4CefRaJEslhaOPM2t4komYvT0+JjfvZ07H",
	"Ba3BwYA/TXhiyafo8O0Wb+Q1zWAiciVDjg1bfQtjVSat7en6gJ8Y535fhDjx5vtJMWNATEToXGlinTwC",
	"5IggS3X00tHBqK/v8MmpSPVu7dxIB1JLx+NZdTbMm7ksFjrdExEMgKMwlBnE6q5RjldLwo0c59C2mz9i",
	"a9UTak3o7rymc05K/7q8HIqOBHYtep+Zc5lY03VqdT5Ql3oLExLKLau6hovQIAQVyciscVPF8W/jPkXs",
	"JBNv29qlsXnClBczpKrfWwX05fTGqk9Lxh17pEXisFp1Uza2c2apqVZbF5/R7lTv1P3crQ+rIUeNd+xe",
	"PjtvGbT5h0x3PQLV772jLbezX5reuVEFvGxYhuPfDYoKSVveXaoitiDbzrdtMGGQdYx+qSk0Sazq1hPx",
	"IM2yWSTG60HeZ9knaT9YN8fqVUNmtWtFnuu8gM38K1UnDi27bV3tOT2ccrJ/SvlS2evtaRydvDlgYuc7",
	"W3by27eHTN58sOwljr49BCvNl+5w1jf7Z3U/89d0HryVLzunvGWv+Q41X6H0H+yQHa6Db6TC7gPk4xgr",
	"EtqaM8sZjfaZqkFGYFBEWJYV2JU0EXafIbnltKkvwwX7Um9ai4N74hOUlaJsvMBG+RNda7J2KbJKYboO",
	"0plzJlxHUvPpNi9K1qacvH1bBSulSanqKxOxtV3N3WOT9f22KMZbR4C/oE7cbEE+RBu++V3336YIGyQr",
	"mdkxFfL08NVK6P+DTmloBS/ATZx6VJZWoKUnnE5oqoijL47ZX3ZFWL8Du8edKVbHcYNwJySvq5FheF/W",
	"RrzV67JVN/nW92QPugT6+Q90CXYJQUOJD//yVverGXXsA7Ed9qvkS7zFrVaBwXYH7nYkS4AoKbFppFA8",
	"Oo2OULP6lTeLDc2cg4/FfCQ7rJjMR+ObXFtemWjIWH2qO8zmzLv6hMonrM2smfGXzy//FwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
